### ISSUE TITLE
GitHub release 0.8.19 missing?

### ISSUE THREAD

**Issue by hartwork** [mozilla/grcov#1145]
Hi!

I noticed that there is a [Git tag `v0.8.19`](https://github.com/mozilla/grcov/releases/tag/v0.8.19) but not a corresponding GitHub Release like [the one for 0.8.18](https://github.com/mozilla/grcov/releases) with binaries for download and all. Has that been a conscious decision, have the [changes since 0.8.18](https://github.com/mozilla/grcov/compare/v0.8.18...v0.8.19) been considered too minor for a release or is a GitHub release for 0.8.19 still coming?

Thanks and best, Sebastian

**Comment by marco-c** [comment]
I had simply forgotten to move it from Draft to Published. I've done it now.

**Comment by hartwork** [comment]
@marco-c thank you!

**Comment by Turbo87** [comment]
@marco-c it looks like the same has happened for 0.8.20 now too

**Comment by marco-c** [comment]
@Turbo87 published!

**Comment by hartwork** [comment]
Thank you! :tada:
