### ISSUE TITLE
It seems that grcov can't work with cxx bridge

### ISSUE THREAD

**Issue by MochiXu** [mozilla/grcov#1175]
My rust project is a FFI library for cpp, it integrates with `cxx` library.
When generate coverage report, errors happened.

```bash
❯ grcov . -s . --binary-path ./target/debug/ -t cobertura --branch --ignore-not-existing -o .                       
03:57:01 [ERROR] A panic occurred at /home/mochix/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/grcov-0.8.19/src/llvm_tools.rs:110: 
Failed to open directory '"./target/debug/"': File system loop found: ./target/debug/build/tantivy_search-125cdd8efd245d38/out/cxxbridge/crate/tantivy_search/build/cargo/build/x86_64-unknown-linux-gnu/relwithdebinfo/build/tantivy_search-eef39e5ef494680d/out/cxxbridge/crate/tantivy_search points to an ancestor ./target/debug/build/tantivy_search-125cdd8efd245d38/out/cxxbridge/crate/tantivy_search
```

**Comment by MochiXu** [comment]
This does nod work even with the ignore field added
```bash
❯ grcov . -s . --binary-path ./target/debug/ -t cobertura --branch --ignore "./target/debug/build/tantivy_search-125cdd8efd245d38/out/cxxbridge/" -o .          
04:48:52 [ERROR] A panic occurred at /home/mochix/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/grcov-0.8.19/src/llvm_tools.rs:110: 
Failed to open directory '"./target/debug/"': File system loop found: ./target/debug/build/tantivy_search-125cdd8efd245d38/out/cxxbridge/crate/tantivy_search/build/cargo/build/x86_64-unknown-linux-gnu/relwithdebinfo/build/tantivy_search-eef39e5ef494680d/out/cxxbridge/crate/tantivy_search points to an ancestor ./target/debug/build/tantivy_search-125cdd8efd245d38/out/cxxbridge/crate/tantivy_search
```

**Comment by wxie7** [comment]
> This does nod work even with the ignore field added
> 
> ```shell
> ❯ grcov . -s . --binary-path ./target/debug/ -t cobertura --branch --ignore "./target/debug/build/tantivy_search-125cdd8efd245d38/out/cxxbridge/" -o .          
> 04:48:52 [ERROR] A panic occurred at /home/mochix/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/grcov-0.8.19/src/llvm_tools.rs:110: 
> Failed to open directory '"./target/debug/"': File system loop found: ./target/debug/build/tantivy_search-125cdd8efd245d38/out/cxxbridge/crate/tantivy_search/build/cargo/build/x86_64-unknown-linux-gnu/relwithdebinfo/build/tantivy_search-eef39e5ef494680d/out/cxxbridge/crate/tantivy_search points to an ancestor ./target/debug/build/tantivy_search-125cdd8efd245d38/out/cxxbridge/crate/tantivy_search
> ```

Hello, may I ask how you ended up resolving it?

**Comment by MochiXu** [comment]
@wxie7 Sure, you can refer to the Gitlab CI configuration I wrote earlier. project: [tantivy-search](https://github.com/myscale/tantivy-search/blob/6be234890b53caed2044518abb69737c48ac99fc/.gitlab-ci.yml#L76C1-L115C31)

**Comment by wxie7** [comment]
> @wxie7 Sure, you can refer to the Gitlab CI configuration I wrote earlier. project: [tantivy-search](https://github.com/myscale/tantivy-search/blob/6be234890b53caed2044518abb69737c48ac99fc/.gitlab-ci.yml#L76C1-L115C31)

Thanks. I found that it might be an issue with the version of grcov. Version 0.8.18 works correctly on my machine, but the latest version 0.8.20 does not. [issue1238](https://github.com/mozilla/grcov/issues/1238)
