### ISSUE TITLE
LCOV output started reporting way too small numbers (while Markdown output shows the expected ones)

### ISSUE THREAD

**Issue by hartwork** [mozilla/grcov#1239]
Hello!

At some point in time LCOV output started reporting way too small numbers while the Markdown output shows the expected ones. Here is proof and more information:

## Markdown output, as expected

```console
$ grcov --binary-path target/debug --source-dir src --ignore '/*' --branch --llvm-path /usr/bin -t markdown -o target/coverage/summary.md .
$ cat target/coverage/summary.md
| file                   | coverage | covered   | missed_lines       |
|------------------------|----------|-----------|--------------------|
| command_line_parser.rs | 100.00%  | 152 / 152 |                    |
| exec.rs                | 100.00%  | 57 / 57   |                    |
| main.rs                | 97.65%   | 208 / 213 | 38, 75, 81, 85, 99 |
| network.rs             | 100.00%  | 157 / 157 |                    |
| logging.rs             | 97.56%   | 160 / 164 | 63-65, 103         |

Total coverage: 98.79%
```

## LCOV output, broken

```console
$ grcov --binary-path target/debug --source-dir src --ignore '/*' --branch --llvm-path /usr/bin -t lcov -o target/coverage/lcov .
$ lcov --list target/coverage/lcov
                              |Lines       |Functions  |Branches    
Filename                      |Rate     Num|Rate    Num|Rate     Num
====================================================================
[/]
command_line_parser.rs        | 7.2%    152| 0.0%    11|    -      0
exec.rs                       |12.3%     57| 0.0%     7|    -      0
logging.rs                    |22.0%    159| 0.0%    33|    -      0
main.rs                       |21.2%    208| 0.0%    44|    -      0
network.rs                    | 7.6%    157| 0.0%    12|    -      0
====================================================================
                        Total:|14.9%    733| 0.0%   107|    -      0
```

## Additional info

- This is with both grcov `0.8.18` and `0.8.19` and `0.8.20`
- This is with LCOV version `2.0-4ubuntu2` and also `2.0-1`
- The code base for this was https://github.com/hartwork/rust-for-it/ .
- There is a related bug https://github.com/hartwork/rust-for-it/issues/171 and pull request https://github.com/hartwork/rust-for-it/pull/181

Best, Sebastian

**Comment by marco-c** [comment]
@hartwork could you try with older grcov versions, so we can figure out what caused this?

**Comment by hartwork** [comment]
@marco-c I experimented with it more and found that even with 0.8.18 from back when I first started using grcov in Jun 2023 at https://github.com/hartwork/rust-for-it/pull/8 produces this issue today. So given the binary contains all the Rust dependencies from that time baked in it seems to mean that either the commands that grcov is calling out to have changed and take part in the problem  (but then I'd expect markdown output to also be affected) or that the LCOV output that grcov 0.8.18 is writing was fine to the eyes of LCOV from back then but no longer is. That's my current best guess: maybe the LCOV output no longer matches today's LCOV. What do you think?

**Comment by hartwork** [comment]
Small update: I'm starting to think that maybe it's the command line output part **of the LCOV command line tool** that broke in the meantime. In the context of Expat CI, I'm [passing the very same file to LCOV's `genhtml` and also `lcov -l`](https://github.com/libexpat/libexpat/blob/master/expat/coverage.sh) and the former produces sane and expected numbers in the HTML report whereas `lcov -l` reports way too small numbers, e.g.:

```
$ time ./coverage.sh
[..]
Rendering HTML report...
# genhtml -o coverage__R_2_6_4-14-ga0dc7d5e coverage__R_2_6_4-14-ga0dc7d5e/coverage.info
--> coverage__R_2_6_4-14-ga0dc7d5e/index.html

Rendering ASCII report...
# lcov -q -l coverage__R_2_6_4-14-ga0dc7d5e/coverage.info
                           |Lines       |Functions  |Branches    
Filename                   |Rate     Num|Rate    Num|Rate     Num
=================================================================
lib/siphash.h              |20.5%     78| 0.0%    16|    -      0
lib/xmlparse.c             | 3.8%   4433| 0.0%   163|    -      0
lib/xmlrole.c              | 8.2%    644| 0.0%    53|    -      0
lib/xmltok.c               | 8.8%    433| 0.0%    32|    -      0
lib/xmltok_impl.c          | 8.0%   1052| 0.0%    84|    -      0
lib/xmltok_ns.c            |43.8%     32| 0.0%    12|    -      0
xmlwf/codepage.c           |    -      0|    -     0|    -      0
xmlwf/readfilemap.c        | 4.5%     22| 0.0%     1|    -      0
xmlwf/xmlfile.c            |14.6%     48| 0.0%     5|    -      0
xmlwf/xmlwf.c              |17.1%    280| 0.0%    15|    -      0
=================================================================
                     Total:| 6.1%   7022| 0.0%   381|    -      0
```
The HTML report however says…

![genhtml](https://github.com/user-attachments/assets/64f59964-9dc9-4b83-ae8e-c2eb508cd0ce)

…which is a huge difference.

I have yet to try with other versions of LCOV than 2.0 but I felt this could be interesting to you already.

**Comment by hartwork** [comment]
Update: This is with **LCOV 2.2**, also totally broken but in a very different way:

```console
# lcov --version
lcov: LCOV version 2.2-1

# lcov -q -l coverage__R_2_6_4-14-ga0dc7d5e/coverage.info
                           |Lines       |Functions  |Branches    
Filename                   |Rate     Num|Rate    Num|Rate     Num
=================================================================
lib/siphash.h              |99.9%      #|99.9%     #|99.9%      #
lib/xmlparse.c             |99.9%      #|99.9%     #|99.9%      #
lib/xmlrole.c              |99.9%      #|99.9%     #|99.9%      #
lib/xmltok.c               |99.9%      #|99.9%     #|99.9%      #
lib/xmltok_impl.c          |99.9%      #|99.9%     #|99.9%      #
lib/xmltok_ns.c            |99.9%      #|99.9%     #|99.9%      #
xmlwf/codepage.c           |99.9%      #|99.9%     #|99.9%      #
xmlwf/readfilemap.c        |99.9%      #|99.9%     #|99.9%      #
xmlwf/xmlfile.c            |99.9%      #|99.9%     #|99.9%      #
xmlwf/xmlwf.c              |99.9%      #|99.9%     #|99.9%      #
=================================================================
                     Total:|99.9%      #|99.9%     #|99.9%      #
Message summary:
  no messages were reported
```
What the hell :smiley: 

I guess I have to take this to LCOV upstream.

The version of LCOV that seems to work in Expat CI is **LCOV 1.15** with the Ubuntu 22.04.5 image.

**Comment by hartwork** [comment]
I have taken the issue to LCOV upstream now at https://github.com/linux-test-project/lcov/issues/335 . Should it be closed as "likely not a bug in grcov" here?
