### ISSUE TITLE
Remove FilePath enum from src/producer.rs

### ISSUE THREAD

**Issue by marco-c** [mozilla/grcov#138]
See https://github.com/mozilla/grcov/pull/137/files#r198485862.

**Comment by akansha2608** [comment]
Hi @marco-c i would like to work on it , can you help me how to getting started?


Thanks

**Comment by marco-c** [comment]
Hey @akansha2608, after you've cloned the repository, make sure you can build the project and successfully run the tests. Once that is done, you can start with this (look at https://github.com/mozilla/grcov/pull/137/files#r198485862 for more details on how to fix it).

**Comment by TaranSinghania** [comment]
@marco-c Can I work on this?

**Comment by marco-c** [comment]
Sure, no need to ask ;)
