### ISSUE TITLE
Option to prepend a path prefix

### ISSUE THREAD

**Issue by gabriel-v** [mozilla/grcov#148]
A command line argument to prepend a prefix to all file paths.

This is useful for getting the full relative paths of the source files referenced in the JaCoCo XML reports.

The JaCoCo XML reports only store the java package information, like `org/mozilla/gecko/browserid/DSACryptoImplementation.java`, but full paths are required: `mobile/android/app/src/test/java/org/mozilla/gecko/browserid/DSACryptoImplementation.java`.

Any preference on the option name? `--add-prefix`?

**Comment by marco-c** [comment]
`--add-prefix` sounds fine!
