### ISSUE TITLE
Add option to rewrite partial paths into complete paths relative to source directory

### ISSUE THREAD

**Issue by gabriel-v** [mozilla/grcov#162]
When collecting Java code coverage, we get filenames that are relative to the Java package root, not the source directory. This means we need functionality for the following:

On startup, if the argument `--rewrite-partial-relative-paths` has been passed, then:
- walk the source directory and record all file paths found
- note the longest path (in number of segments), let this be `N`
- initialize hash maps `map[1]` to `map[N]`
- for all paths:
  - for all path suffixes:
    - X is the number of segments in the suffix
    - add the mapping `suffix -> path` to `map[X]`

Then, for each file path:

- for `i` from `N` to `1`:
  - if the path is in `map[i]`, then rewrite it to `map[i][path]` and continue to next file

All paths should be relative to the source directory. Where should this rewriting go? Is the end of [the rewrite_paths function](https://github.com/mozilla/grcov/blob/376ab00c79682a9138f54d7756e503babf140af3/src/path_rewriting.rs#L147) the place to do this?

**Comment by marco-c** [comment]
Another possibility is to see the source files as a tree, reversed (the top of the tree being the files, the bottom of the tree being the root directory).

We can use a trie (https://crates.io/crates/tst) to make it quite simple:
```Rust
# Store reversed paths.
let m = tstset! {
    "backwards.java/path/home",
    "reversed.java/path/2/home",
    "reversed.java/path/1/home",
};

# We should find only one here, right?
for key in m.prefix_iter("reversed.java/path/1") {
    println!("{}", key);
}
```
