### ISSUE TITLE
Rename ignore-dir option

### ISSUE THREAD

**Issue by marco-c** [mozilla/grcov#193]
Since it's actually a glob.

**Comment by NerdyPepper** [comment]
A couple of suggestions:

`-I` - used by `ls(1)` and `tree(1)`  
`--ignore=pattern` - used by `ls(1)`
`--exclude=pattern` - used by `grep(1)`

Let me know what you think @marco-c

**Comment by marco-c** [comment]
I'd go with `--ignore`, what do you think @calixteman ?
