### ISSUE TITLE
Use if-let chains when available to clean up some code

### ISSUE THREAD

**Issue by marco-c** [mozilla/grcov#195]
https://github.com/rust-lang/rust/issues/53667

**Comment by crawfordleeds** [comment]
Hey @marco-c, curious about any performance or stylistic improvements for doing this. My understanding of if-let's are primarily for handling a single match pattern and ignoring the rest. As I look through the codebase, most comparisons seem to have two match patterns, e.g. in lib.rs:

```rust
match result.lines.entry(line_no) {
       btree_map::Entry::Occupied(c) => {
           *c.into_mut() += execution_count;
       }
       btree_map::Entry::Vacant(v) => {
           v.insert(execution_count);
       }
};
```

I could change that to and if-let like so:

```rust
if let btree_map::Entry::Occupied(c) = result.lines.entry(line_no) {
       *c.into_mut() += execution_count;
}
if let btree_map::Entry::Vacant(v) = result.lines.entry(line_no) {
       v.insert(execution_count);
}
```

Is this just the preferred syntax now, or are there performance improvements? Happy to start contributing to this project with this (feel free to assign to me), just wondering to get feedback on any technical improvements I don't know about or if this was just stylistic preference.

Cheers!

**Comment by marco-c** [comment]
It's just a stylistic preference, but not to apply in cases like the one you mentioned.

A good example is https://github.com/mozilla/grcov/blob/5d6715d3779ec43a21f1568fc945c31684b2831f/src/gcov.rs#L7, where:
```
    match env::var("GCOV") {
        Ok(s) => s,
        Err(_) => "gcov".to_string(),
    }
```
would become:
```
if let Ok(s) = env::var("GCOV") {
  s
} else {
  "gcov".to_string()
}
```

**Comment by crawfordleeds** [comment]
Great, thanks for the feedback. I'll take a shot at this and open a PR shortly. Thanks!
