### ISSUE TITLE
Make source_dir CWD by default

### ISSUE THREAD

**Issue by marco-c** [mozilla/grcov#205]

**Comment by mrbuzz** [comment]
Hi! I'd like to work on this. 
Would changing `grcov/src/main.rs:52`  
from  
`let mut source_dir = "";`
to 
`let mut source_dir = std::env::current_dir()?;`
be a good starting point?

**Comment by marco-c** [comment]
Hey @mrbuzz, yes that should work! Once you've done that, you could also update .travis.yml and appveyor.yml to stop using the "-s ." parameter.

**Comment by marco-c** [comment]
This can be a bit risky for some use cases, so it's better to avoid it and let users define their src dir.
