### ISSUE TITLE
Don't run travis CI when modifying appveyor.yml

### ISSUE THREAD

**Issue by calixteman** [mozilla/grcov#207]
https://github.com/facebook/react/pull/2000/files

**Comment by marco-c** [comment]
And likewise, don't run Appveyor build when modifying .travis.yml.

**Comment by sahitpj** [comment]
May I work on this issue, if not assigned?

**Comment by marco-c** [comment]
Fixed by #218.

**Comment by marco-c** [comment]
Reopening because #218 has been reverted.

**Comment by rei2hu** [comment]
I looked at the revert reason. Is there a specific set of files where Travis should run but it doesn't? At a glance, it looks like this would only happen if each file changed contained `appveyor.yml` in its name.

**Comment by marco-c** [comment]
> I looked at the revert reason. Is there a specific set of files where Travis should run but it doesn't? At a glance, it looks like this would only happen if each file changed contained appveyor.yml in its name.

I don't remember exactly when they were skipped, but IIRC they were skipped for any change. You can test by submitting a test PR applying the reverted patch and modifying some random files.

**Comment by marco-c** [comment]
We are no longer using Appveyor.
