### ISSUE TITLE
Don't replace newlines in coverage report on appveyor

### ISSUE THREAD

**Issue by marco-c** [mozilla/grcov#209]
It's probably unnecessary, we should check if it actually is unnecessary: https://github.com/mozilla/grcov/blob/32c277af9559203f0af4d6aaa71d5ad496851dab/appveyor.yml#L66

**Comment by LucianaMarques** [comment]
Hi @marco-c , I'd like to give it a try. Has anyone already been assigned to this? Thank you

**Comment by marco-c** [comment]
Hey @LucianaMarques, sure, it's still available! If you don't see anyone assigned on the GitHub interface on the right, or if you don't see a PR open for an issue, you can assume that it is not assigned.

**Comment by k-conway** [comment]
Hi @marco-c I'm brand new at contributing to Open Source and was thinking of grabbing this one. Can you point me at contribution instructions and guidelines?

**Comment by marco-c** [comment]
@k-conway are you already familiar with how git and GitHub work?

**Comment by k-conway** [comment]
Thank you @marco-c 

I am familiar with git and GitHub. I've been able to contribute to a different project on GitHub but was having trouble getting process and info in this case!

**Comment by marco-c** [comment]
@k-conway I asked simply because I needed to know where to start :P
We follow the usual GitHub flow, so you can just submit a PR when you are able to fix this issue.

The project is in Rust, but this particular issue is an issue in our CI and needs to be fixed in the yaml file I linked in the first comment. The documentation for building and testing the project are easy (https://github.com/mozilla/grcov#build--test), but they are not necessary for this particular issue (you'll need to actually submit the PR to see if the CI behaves correctly or not).

**Comment by k-conway** [comment]
thank you so much @marco-c ! I appreciate the info as well as you checking to see what level of detail I was looking for. 

I'll take a pass at this.

**Comment by marco-c** [comment]
We are no longer using Appveyor.
