### ISSUE TITLE
Running grcov with a Firefox source directory containing a build directory fails

### ISSUE THREAD

**Issue by marco-c** [mozilla/grcov#210]
grcov ~/src/firefox/obj/ff-asan-release/ -s ~/src/firefox -t coveralls --token 1111111 --commit-sha 20181015165802
thread 'main' panicked at 'Only one file in the repository should end with storage/Variant_inl.h (storage/Variant_inl.h and obj-x86_64-pc-linux-gnu/dist/include/mozilla/storage/Variant_inl.h both end with that)', src/path_rewriting.rs:143:13

I think the solution to this is skipping symlinks when generating the map for partial paths.

**Comment by calixteman** [comment]
in this particular case, I think we should exclude obj-*** directory from the mapping because finally it's the build directory. 
And what will we do if instead of having a symlink we have copied file ?
