### ISSUE TITLE
Assign names to threads

### ISSUE THREAD

**Issue by marco-c** [mozilla/grcov#216]
We should assign names to threads when we create them, to make debugging easier when there is a problem.

**Comment by LucianaMarques** [comment]
Hi Marco! I'd like to give this a try!

What I was thinking was to change the main.rs file in the part that it has a loop to create threads (around line 280), and add a thread name with the Builder type mentioned in: https://doc.rust-lang.org/std/thread/

I didn't read the whole file yet, but I would start from there. Does this makes sense?

**Comment by calixteman** [comment]
@LucianaMarques yep it makes sense
@marco-c why having a name will help here ?

**Comment by LucianaMarques** [comment]
I just opened a pull request on this.
