### ISSUE TITLE
Prettify all JSON expected files under tests/

### ISSUE THREAD

**Issue by marco-c** [mozilla/grcov#226]
Instead of https://github.com/mozilla/grcov/blob/aee0b46ebcf4e4f37482b4e3d6acb8cf832c63fa/tests/include2/expected_llvm_7_linux.coveralls, they should all be like https://github.com/mozilla/grcov/blob/71c71beebee5ad62329aaea2d2df88de366bbe5d/tests/basic/expected_llvm.coveralls.

**Comment by arshadkazmi42** [comment]
@marco-c Is it up for grab? I can take this up

**Comment by marco-c** [comment]
@harshagarwal7272 started on this in #228, but I'm not sure if they intend on continuing the work. @harshagarwal7272 do you want to keep working on this?

**Comment by Mika-net** [comment]
@marco-c if it's alright I will start on this #228 and submit a PR with it either today or tomorrow.

**Comment by marco-c** [comment]
Sure, feel free, that PR was abandoned.

**Comment by Mika-net** [comment]
@marco-c I've submitted a PR, lmk if anything looks off.

**Comment by marco-c** [comment]
The ADE files (*.ade) should not be prettified (the tests are reading one line at a time: https://github.com/mozilla/grcov/blob/6bc906f1065e51ebb78c1a27fbe8535228ebba39/tests/test.rs#L221-L231). Sorry, I forgot to mention that :(

**Comment by Mika-net** [comment]
That would explain that, no worries. I'll try with just the coveralls

**Comment by marco-c** [comment]
> I'll try with just the coveralls

covdir should be OK to prettify too
