### ISSUE TITLE
Clean up code to handle cli options

### ISSUE THREAD

**Issue by marco-c** [mozilla/grcov#23]
Instead of handling them manually, we could use some package (e.g. clap).

**Comment by svensevenslow** [comment]
Hi! I'd like to work on this.

**Comment by marco-c** [comment]
Hello @svensevenslow! The code that handles CLI options is here: https://github.com/marco-c/grcov/blob/master/src/main.rs#L46.

**Comment by svensevenslow** [comment]
Hi! Which would you think would a better idea to implement it, making a yml file and doing something like load_yml!() in the main.rs file or adding something like this .arg(Arg::with_name(" ")) in the main.rs file

**Comment by marco-c** [comment]
It would be nice to do it with YAML if feasible, otherwise the second option is fine too.

**Comment by svensevenslow** [comment]
@marco-c Can you clarify what this line of code does https://github.com/marco-c/grcov/blob/master/src/main.rs#L179.

**Comment by marco-c** [comment]
If you run `grcov` without options, you'll see:
```
Usage: grcov DIRECTORY_OR_ZIP_FILE[...] [-t OUTPUT_TYPE] [-s SOURCE_ROOT] [-p PREFIX_PATH] [--token COVERALLS_REPO_TOKEN] [--commit-sha COVERALLS_COMMIT_SHA] [--keep-global-includes] [--ignore-not-existing] [--ignore-dir DIRECTORY] [--llvm] [--path-mapping PATH_MAPPING_FILE] [--branch]
You can specify one or more directories, separated by a space.
```

That part of the code is what handles the "DIRECTORY_OR_ZIP_FILE[...]" parameters.

E.g. if you run `grcov DIR1 DIR2`, `paths` will be a vector containing `DIR1` and `DIR2`.

**Comment by svensevenslow** [comment]
@marco-c I am having a bit of a problem. How to I get all the names of the directories and push it onto the paths vecotor. I tried using 
```
             let dir: Vec<_> = matches.values_of("DIRECTORY_OR_ZIP_FILE").unwrap().collect();
             //after this what to do
```
I tries a few things but I'm running into errors while building
My YAML file has the following 
```
- DIRECTORY_OR_ZIP_FILE:
    help: specify one or more directories, separated by a space.
    required: true
    multiple: true
```

**Comment by marco-c** [comment]
@svensevenslow unfortunately I'm not familiar with the Clap library, the only thing I can suggest is to look at their documentation and examples.

**Comment by svensevenslow** [comment]
@marco-c Hi! I have opened a PR (https://github.com/marco-c/grcov/pull/80). Some of the tests are failing while running `cargo test`. I am not sure why the tests are failing, could you help me out?

**Comment by marco-c** [comment]
@LucianaMarques yes! If there is no PR open, then you can assume the issue is free to work on.

**Comment by LucianaMarques** [comment]
> Hello @svensevenslow! The code that handles CLI options is here: https://github.com/marco-c/grcov/blob/master/src/main.rs#L46.

@marco-c is this still the correct?

**Comment by LucianaMarques** [comment]
Also, how can I possibly test this?

**Comment by marco-c** [comment]
> @marco-c is this still the correct?

Yes, if you open that link you'll see that it's still the code to handle CLI options.

> Also, how can I possibly test this?

This is a refactoring, so any option that works now should work in the same way after the change. You can test by running grcov and making sure that all options work as they worked before your changes.

**Comment by marco-c** [comment]
https://github.com/mozilla/grcov/pull/80 was a PR which was started to fix this, but it was since abandoned.
