### ISSUE TITLE
Evaluate using hashbrown crate

### ISSUE THREAD

**Issue by marco-c** [mozilla/grcov#234]
https://github.com/Amanieu/hashbrown

**Comment by LucianaMarques** [comment]
Hi @marco-c, could you provide a better description about this issue? Are we supposed to implement this tool in the project?

It sounds interesting but I don't know from where to start.

**Comment by marco-c** [comment]
@LucianaMarques the goal would be to replace the btree map / hash map usage in src/lib.rs with usage of the hashbrown crate.

**Comment by LucianaMarques** [comment]
Ok, thank you, I'm working on this.

**Comment by NerdyPepper** [comment]
@marco-c, would this be a duplicate of #283, now that `std::collections::HashMap` uses hashbrown by default?

In any case #324, addresses this, let me know what you think!

**Comment by marco-c** [comment]
Yes, definitely a duplicate.
