### ISSUE TITLE
Evaluate using FxHashMap instead of HashMap

### ISSUE THREAD

**Issue by marco-c** [mozilla/grcov#235]
We don't need a cryptographically secure implementation.

**Comment by jarkyll** [comment]
@marco-c Is this bug up for grabs?

**Comment by marco-c** [comment]
Yes, any bug which is still open and has no PR associated to it is up for grabs!

**Comment by lawrencek0** [comment]
I'd like to work on this issue

**Comment by marco-c** [comment]
@lawrencek0 sure, feel free to work on it!
