### ISSUE TITLE
Confusing results with the current version

### ISSUE THREAD

**Issue by adrian17** [mozilla/grcov#260]
I made a basic Rust repo and used a Travis config identical to the one in README.md.

The results for several versions of the file were:
https://codecov.io/gh/adrian17/grcov_test/src/7fa30e1d4ef0b5a126b26c151d0ee1c5ffeed876/src/lib.rs
https://codecov.io/gh/adrian17/grcov_test/src/db692c67e80c869aaee0fb75ea946b5db0d1545e/src/lib.rs
https://codecov.io/gh/adrian17/grcov_test/src/7357431d26b17ed101c3521ca9dab8adac0d3956/src/lib.rs

Examples in a real repo:
https://codecov.io/gh/RustPython/RustPython/src/e2ee9332560debf0483da81d2a72f7f05ded0fae/vm/src/macros.rs
https://codecov.io/gh/RustPython/RustPython/src/e2ee9332560debf0483da81d2a72f7f05ded0fae/vm/src/frame.rs#L1112

I can observe:
- empty lines being marked as not-covered
- macro declaration and some of definition lines marked as not-covered
- parts of macro invocation marked as not-covered or partially-covered
- assert_eq! marked as partially-covered (this one is understandable, as it probably contains a branch that wasn't taken. Special handling of tests would be nice, but is out of scope of this issue; I only mentioned it for completeness).

I would expect all three commits to have 100% coverage.

**Comment by calixteman** [comment]
@adrian17, see my answer here: https://github.com/mozilla/grcov/issues/249#issuecomment-465154051
Instrumentation is made on LLVM side which use some information gave by the frontend (rustc here).
So I'd say here, that the things you're observing here are related to incorrect information we've in gcno files.
The best way to try to "debug" that stuff is to analyze the generated lcov.info file, see what's wrong in it and compare to what we've in gcno/gcda files.
For example, if in gcno/gcda you see that line X in file foo.rs has a non-zero counter and you don't see line X in lcov.info, definitely it's a grcov bug.
I added the coverage for RustPython and as far as I remember, results were almost correct, but few days ago I noticed a lot of strange red lines... after quick investigation, I'd say that there is an issue an codecov.io side... but not sure, I need to take more time to have a strong opinion about this.

**Comment by calixteman** [comment]
In analyzing your data, I finally managed to find out a bug in grcov:
https://github.com/mozilla/grcov/issues/262

**Comment by mleonhard** [comment]
I had this problem with `rustc 1.49.0-nightly (ffa2e7ae8 2020-10-24)`.  It went away after:
1. `cargo clean`
1. `rm -rf target/`
1.  restarting my editor (CLion)

**Comment by marco-c** [comment]
The main bug has been fixed here by the same fix as for #262 (that is, #264).

Some of those problems could be fixed by source-based coverage, I've recently added support for it in grcov (version 0.6.0). Short explanation at https://marco-c.github.io/2020/11/24/rust-source-based-code-coverage.html, docs at https://github.com/mozilla/grcov#example-how-to-generate-source-based-coverage-for-a-rust-project, full example at https://github.com/marco-c/rust-code-coverage-sample.

See also #476 for possible workarounds should you need to still use gcov-based coverage.
