### ISSUE TITLE
Support excluding some lines, functions, macros, branches from coverage report

### ISSUE THREAD

**Issue by adrian17** [mozilla/grcov#261]
This is a feature request.
lcov has special markers that can be used to exclude parts of code from coverage report. For example, LCOV_EXCL_LINE, LCOV_EXCL_BR_LINE and their START/STOP multiline variants.

It would be nice to have something like this here too.

For example, macros sometimes generate always-true branches that grcov will report as partially-covered. In this case, it would be nice to be able to explicitly exclude them (well, code generated by them) from coverage report.

**Comment by TimDiekmann** [comment]
It would also be nice, if one could exclude tests. Every `assert!` results in a partially covered branch. While this is absolutely desired in real code, in tests it isn't.

**Comment by marco-c** [comment]
You could try source-based coverage, I've recently added support for it in grcov (version 0.6.0). Short explanation at https://marco-c.github.io/2020/11/24/rust-source-based-code-coverage.html, docs at https://github.com/mozilla/grcov#example-how-to-generate-source-based-coverage-for-a-rust-project, full example at https://github.com/marco-c/rust-code-coverage-sample.

**Comment by andrewdavidmackenzie** [comment]
Related to this (I couldn't figure it out from the docs, sorry...) is there a way to exclude the tests module?

in kcov (providing you have the tests module always at the end of the file) you can explcude them all using:
```
--exclude-region='#[cfg(test)]:#[cfg(testkcovstopmarker)]' "target/cov/$(basename $$file)"
```

**Comment by marco-c** [comment]
@andrewdavidmackenzie you should be able to use `--excl-start` and `--excl-stop` for this purpose.

**Comment by andrewdavidmackenzie** [comment]
Ok, I will need to figure out how to use them. Do you have any examples?

**Comment by marco-c** [comment]
@andrewdavidmackenzie there is some discussion in #416 that might be of help. I'd appreciate if you can write something down while you explore the usage of those options (#610).
