### ISSUE TITLE
Compilation broken with edition 2018

### ISSUE THREAD

**Issue by calixteman** [mozilla/grcov#263]
Just add edition = "2018" in Cargo.toml... and see what happens

**Comment by Sylfrena** [comment]
Hey! I tried adding the edition as 2018 to the Cargo.toml . It resulted in a total build failure as the code for grcov is written in Rust 2015. I tried using  `cargo fix --edition-idioms` , and `cargo fix --edition-idioms --allow-dirty`  but that resulted in build failure as well. I am a beginner with Rust and would like to work on this issue but am unable to go ahead from here.

**Comment by marco-c** [comment]
Hello @Sylfrena, we can't really help if you don't ask us a specific question :smile: 

Working on this issue will mean building with edition 2018 and fixing the build failures one by one.

**Comment by Sylfrena** [comment]
@marco-c 
Oh! I think I can start trying to solve the build errors individually. Thanks for the heads up!

**Comment by Atul9** [comment]
@calixteman @marco-c I have opened up a PR for this #280 please check
