### ISSUE TITLE
Define alias for some variable types

### ISSUE THREAD

**Issue by marco-c** [mozilla/grcov#281]
As shown in #252, we are using some data types directly, which makes it hard when you want to switch to some other implementation of the same data type. E.g. in #252, we had to change a lot of places just to switch from HashMap to FxHashMap.

We should do something like https://github.com/mozilla/grcov/blob/14e4c76fd6951947c9406b404b715293a2104626/src/defs.rs#L51, defining aliases for specific usages so that when we want to try a different implementation of a data type we don't have to change all the code sites where the type is used.

**Comment by lawrencek0** [comment]
Would it be alright if I work on this?

**Comment by marco-c** [comment]
> Would it be alright if I work on this?

Sure, feel free!
