### ISSUE TITLE
Use rust hashmap instead of fxhashmap

### ISSUE THREAD

**Issue by calixteman** [mozilla/grcov#283]
Recently, hashbrown (https://github.com/rust-lang/hashbrown) has been included in rust-lang so according to the benchmark (https://github.com/rust-lang/hashbrown#performance) we should at some point evaluate and probably use the rust HashMap.

**Comment by eddyb** [comment]
`FxHashMap` is the `std` `HashMap`, with a different hasher (cheaper and deterministic, at the cost of removing DoS protection).

I'm not sure anything needs to be done here, I can't imagine the default hasher being faster.
