### ISSUE TITLE
Add fuzzing team's format as output

### ISSUE THREAD

**Issue by La0** [mozilla/grcov#285]
This is needed to start working on a better code coverage backend.

The output should be in JSON, and will be stored on a remote storage (S3), by the code-coverage bot from release-services.

The CLI arg could be `--output mozilla` or `--output mozilla-fuzzing`

## Excerpt from the [Code Coverage for fuzzing doc](https://docs.google.com/document/d/1rf2lWgLmyynhXert0-K2KMS-No8scggi1oAcoPiWjvk/edit#)

The server-side structure can be described by the following recursive definition:

* pathObject
  * int: linesTotal
  * int: linesCovered
  * int: linesMissed
  * float: coveragePercent
  * dict(name -> pathObject): children **iff** pathObject is a directory
  * list(int): coverage **iff** pathObject is a file
  * string: name

The `coverage` property is a list where each index represents the respective line in the file, starting with line 0 as the first line. If the value at a certain index is `null`, that means the line is not coverable. If the value is a positive integer or zero, then the value indicates how often the line has been covered.

Fields `linesMissed` and `coveragePercent` are redundant but we can save these calculations by just doing them once and storing the results, rather than having to make all of the calculations in the client on every display.

The name field is also redundant because it is identical to the key in the dict pointing to this pathObject, but it greatly helps the UI to have this property available.

**Comment by marco-c** [comment]
Duplicate of #253.
