### ISSUE TITLE
Generated source files show up at toplevel

### ISSUE THREAD

**Issue by choller** [mozilla/grcov#288]
We recently noticed that several generated C/C++ source files show up as being on the top level, rather than the sub directory where they belong, e.g.:

    🐳  docker ~ # grcov /home/worker/firefox/ -t coveralls+ -p /builds/worker/workspace/build/src --token X --commit-sha Y > tmp.json && python -m json.tool tmp.json | grep bd_lf_apply_tmpl.c

    "name": "8bd_lf_apply_tmpl.c",

    🐳  docker ~ # find firefox/ | grep 8bd_lf_apply_tmpl
    firefox/media/libdav1d/8bd_lf_apply_tmpl.gcno
    firefox/media/libdav1d/8bd_lf_apply_tmpl.gcda

The expected behavior would be that `media/libdav1d/8bd_lf_apply_tmpl.c` is outputted for `name`. The respective `gcno/gcda` files are attached.

[8bd_lf_apply_tmpl.zip](https://github.com/mozilla/grcov/files/3224008/8bd_lf_apply_tmpl.zip)

**Comment by marco-c** [comment]
The source path information in the file seems to be missing the directory.

**Comment by choller** [comment]
> The source path information in the file seems to be missing the directory.

Maybe if the information is entirely missing, grcov could use the directory where the gcno file is located (minus the path specified on the command line).

**Comment by marco-c** [comment]
The info is there, but it just states the path (`        -:    0:Source:8bd_lf_apply_tmpl.c`)

**Comment by choller** [comment]
So either we can somehow fix the produced gcno files or we add an option to grcov to guess the directory based on the gcno/gcda location if the file is toplevel.
