### ISSUE TITLE
Be able to skip errors and produce a report 

### ISSUE THREAD

**Issue by calixteman** [mozilla/grcov#299]

**Comment by La0** [comment]
This is happening a lot lately: got ~ 10 runs in production aborting because of this :cry: 

@calixteman Maybe we can work together on that one next week ?

**Comment by calixteman** [comment]
I'll do it this week. My plan is to add logging and log instead of fail

**Comment by marco-c** [comment]
We should try to log from which file (and which zip) the error is coming from and log the error on Sentry, so we can see if there is a pattern.

**Comment by marco-c** [comment]
(My guess is the Firefox process getting killed by the test harness for some reason, e.g. timeout or something like that)

**Comment by La0** [comment]
Is sentry support available in grcov, or should that be done by the code
coverage bot ?

**Comment by calixteman** [comment]
It exists a crate for sentry: https://docs.sentry.io/platforms/rust/
It seems possible to use sentry with log crate: https://docs.sentry.io/platforms/rust/log/ and so according to the passed options we can then log to a file, std(err|out) or sentry.

**Comment by marco-c** [comment]
I'd make grcov "dumb" and just log normally, and the code coverage bot log to Sentry (so we can easily switch to something else if we want, e.g. having a dashboard like the static analysis one).

**Comment by calixteman** [comment]
@marco-c that's my plan: make an agnostic log and just change the way to output the results according to options.

**Comment by marco-c** [comment]
Fixed by #304.
