### ISSUE TITLE
Add `cargo clippy` pre-commit hook

### ISSUE THREAD

**Issue by ghost** [mozilla/grcov#306]
Per pull request #305, we have added pre-commit hooks for formatting and testing. Clippy was included but commented out due to a large number of errors and warnings that require resolution with clippy. The consensus seems to be that we should resolve those errors/warnings and include clippy.

**Comment by marco-c** [comment]
Fixed by #309.

**Comment by crawfordleeds** [comment]
Hey @marco-c, I'm afraid I may have misled you on PR #309. There was one remaining issue with running clippy. I tried to add it as part of a review but that probably wasn't clear enough.

With the current state of the repo, if you run `cargo clippy --all-targets --all -- -D warnings` one error lingers. This makes it such that the pre-commit hook will fail so people will have to commit with the `--no-verify` flag until this is resolved.

```
error: trait objects without an explicit `dyn` are deprecated
   --> src/producer.rs:141:45
    |
141 |     fn check_file(file: FilePath, checker: &Fn(&mut dyn Read) -> bool) -> bool {
    |                                             ^^^^^^^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn Fn(&mut dyn Read) -> bool`
    |
    = note: `-D bare-trait-objects` implied by `-D warnings`

error: trait objects without an explicit `dyn` are deprecated
   --> src/producer.rs:141:45
    |
141 |     fn check_file(file: FilePath, checker: &Fn(&mut dyn Read) -> bool) -> bool {
    |                                             ^^^^^^^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn Fn(&mut dyn Read) -> bool`
    |
    = note: `-D bare-trait-objects` implied by `-D warnings`

error: aborting due to previous error

error: Could not compile `grcov`.
warning: build failed, waiting for other jobs to finish...
error: aborting due to previous error

error: Could not compile `grcov`.
```

When I try to just add the `dyn` keyword to the argument, per the help message, I see a whole new can of errors. Do you have any recommendations on how to address that? Thanks!

**Comment by marco-c** [comment]
Oh, ok. I've committed f0ed4cdcdcdfda9132bbe0be60200d22e922aeec to temporarily disable Clippy (so that other contributors won't be confused if pre-commit fails).

I think the "dyn" error is just hiding the others. When you add "dyn", Clippy will show the other errors too, which have to be fixed one at a time.

**Comment by marco-c** [comment]
Note: currently Clippy is running on all files even if you just modify one. We should make it only run on the files modified by the commit.

**Comment by marco-c** [comment]
> Note: currently Clippy is running on all files even if you just modify one. We should make it only run on the files modified by the commit.

Or maybe not, as errors could be introduced in a different file than the one you're modifying if they have a relation.

**Comment by crawfordleeds** [comment]
Thanks for the feedback Marco, and sorry for the miscommunication. I'll dive into the issues that arise after adding `dyn` and have a PR to fix this shortly.

I agree on having clippy review all files with pre-commit. Let me know if you think that becomes cumbersome and I'll make a fix.

Thanks!
