### ISSUE TITLE
Integration Tests Failing

### ISSUE THREAD

**Issue by crawfordleeds** [mozilla/grcov#308]
I'm currently having issues getting all the integration tests to pass. I've had this issue since I first cloned the repository which I have mostly ignored. However, it is now causing problems now that the pre-commit hooks are enabled on this repository. Since it doesn't pass the tests I have to commit with --no-verify.

I was hoping to get some help either identifying the issue on my machine or determining a path forward to fix if this is an issue with the project (seems unlikely since all CI tools pass the tests).

Here's the last of the output when I run `cargo test`:

```
thread 'test_integration' panicked at 'assertion failed: `(left == right)`
  left: `Array([Null, Null, Null, Null, Number(1), Null, Number(4), Number(1), Null, Number(1), Number(2)])`,
 right: `Array([Null, Null, Null, Null, Number(1), Null, Number(1), Number(1), Null, Number(1), Number(1)])`: Got correct coverage for "main.cpp"', tests/test.rs:302:13
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.


failures:
    test_integration

test result: FAILED. 3 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test test'
```

I've tried this with a few different versions of rustc including 1.32.0 nightly, 1.36 stable, and 1.38.0 nightly all with the same result.

Does anyone have any thoughts on what the issue may be? Thanks for the help!

**Comment by marco-c** [comment]
What version of LLVM and GCC do you have?

BTW, since integration tests are hard to set up at the moment, we should make pre-commit not run them.

**Comment by calixteman** [comment]
FYI, the way to run all the tests:
GCOV=gcov-7 CLANG_CXX=clang++-9 GCC_CXX=g++-7 cargo test

The integration tests are failing with a g++ version upper than 8 (included).

**Comment by crawfordleeds** [comment]
Thank you both for the feedback.

@marco-c, I'm on macOS and running Apple LLVM version 10.0.1 (clang-1001.0.46.4). I'm actually not sure what version of LLVM that corresponds to - I think they stopped sharing that in Apple LLVM version 7. I did some searching and [this table](https://en.wikipedia.org/wiki/Xcode#Toolchain_versions) seems to imply LLVM version 7.0.0.

I've never done it, but do you recommend installing LLVM directly either from source or through homebrew?

I'll work on removing the integration tests from pre-commit. That'll be helpful for me.

@calixteman I get the same error when running with all those environment variables. Seems like my issue is related to LLVM/GCC/g++ versions? Once that's resolved, are those environment variables necessary and if so, should we add them to the README?

Thanks again!

**Comment by marco-c** [comment]
> @marco-c, I'm on macOS and running Apple LLVM version 10.0.1 (clang-1001.0.46.4). I'm actually not sure what version of LLVM that corresponds to - I think they stopped sharing that in Apple LLVM version 7. I did some searching and this table seems to imply LLVM version 7.0.0.

On Travis (where the integration tests are passing), we have `Apple LLVM version 9.1.0 (clang-902.0.39.2)`.

> I've never done it, but do you recommend installing LLVM directly either from source or through homebrew?

I've never done that myself either (I'm on Linux). I'd try with homebrew first, and if that doesn't work I'd resort to building LLVM from source (then when you run grcov's unit tests, you can simply add the clang obj dir to your PATH).

**Comment by calixteman** [comment]
The values of the env vars depend of the versions of gcc/clang you've on your machine.
Finally these values are just the name of the commands to run g++, clang++ and gcov (coming with gcc).
