### ISSUE TITLE
How to exclude dependencies from HTML report?

### ISSUE THREAD

**Issue by blaesus** [mozilla/grcov#317]
So I have a Rust project that have some dependencies (and dependencies' dependencies).

Here are the commands I used to gather test coverage:

```
export CARGO_INCREMENTAL=0
export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads"
cargo +nightly build --verbose $CARGO_OPTIONS
cargo +nightly test --lib --verbose $CARGO_OPTIONS

grcov . --ignore-dir deps -t lcov > /tmp/lcov.info
genhtml -o tests/coverage-report/ --show-details --highlight --ignore-errors source --legend /tmp/lcov.info

rm /tmp/lcov.info
```

The problem is that the output HTML contains coverage information about dependencies, such as `libcore`, `hyper`, `crossbeam` and many others.

Is there an option somewhere where I can filter out these external dependencies from the HTML report?

[The answers on SO](https://stackoverflow.com/questions/6652779/looking-for-a-way-to-exclude-files-used-by-geninfo-genhtml) about excluding dependencies from `genhtml` directed me to `lcov`, which I assume is equivalent to `grcov` here.

**Comment by marco-c** [comment]
You can use the `--ignore-dir` option.

**Comment by lobianco** [comment]
This doesn't answer OP's question. As you can see from their example they did try `--ignore-dir` to no avail. 

I'm in a similar boat. I zip up only the `.gc*` files that pertain specifically to the members of my workspace (e.g. only the files that are prefixed with a member's name) and run `grcov` on it:

```bash
grcov grcov.zip --source-dir . --llvm --branch --ignore-not-existing --output-file grcov.info
```

When I create a report from `grcov.info` it contains coverage information for several dependencies that have no associated `.gc*` files in the original archive. `--ignore-dir` wouldn't help in this case. 

`lcov` has [`--no-external`](https://stackoverflow.com/a/16245520/969967) which seems to solve this problem. Is there a way to accomplish something similar in `grcov`? Or is this perhaps a configuration issue with `genhtml`?

**Comment by calixteman** [comment]
--ignore-dir (now --ignore) is a glob pattern so if you want to ignore all paths starting with a "/" then use "/*" or if you want to ignore files under deps then use "deps/*"

**Comment by lobianco** [comment]
Thanks, I understand how the flag works. But it is not a solution to this problem. Perhaps if I provide more context that will be helpful. 

Here is a simplified representation of my build steps:

```bash
# generate .gc* files
CARGO_INCREMENTAL=0 \
RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Clink-dead-code -Coverflow-checks=on -Zno-landing-pads"  \
cargo +nightly test

# zip up only the .gc* files that i'm interested in
zip -0 grcov.zip `for CRATE in "my-crate-1" "my-crate-2" "my-crate-3"; do find target/debug -name "${CRATE}*.gc*" -print; done`

# grcov.zip now contains the following:
#
# target/debug/deps/my-crate-1-5a3398fccb895aa1.gcda
# target/debug/deps/my-crate-1-5a3398fccb895aa1.gcno
# target/debug/deps/my-crate-2-7f4fad2d0efa64c9.gcda
# target/debug/deps/my-crate-2-7f4fad2d0efa64c9.gcno
# target/debug/deps/my-crate-3-793896cf85ac91a0.gcda 
# target/debug/deps/my-crate-3-793896cf85ac91a0.gcno 
#
# (e.g. no external dependencies included in the archive)

# run grcov 
grcov grcov.zip --source-dir . --llvm --branch --ignore-not-existing --output-file grcov.info

# generate html report
genhtml --output-directory target/grcov --show-details --highlight --ignore-errors source --legend grcov.info
```

After running the html report I still notice code coverage results for external dependencies that _don't exist_ in `grcov.zip`. Adding `--ignore-dir "target/debug/deps/*` to the `grcov` command has no effect, those extraneous results still exist in the report:

![PNG image-DD26295904DE-1](https://user-images.githubusercontent.com/1753971/66069205-bff9ea00-e503-11e9-9668-b062fab2dd18.png)

The results that I care about are obfuscated. The unobfuscated results are the external dependencies I'm trying to get rid of. I believe they are direct dependencies of my files in question (e.g. `my-crate-1`, `my-crate-2`, `my-crate-3` from above) but I don't want them included in the report. Is there any way to achieve this currently?

**Comment by calixteman** [comment]
try to add --ignore-dir="/*" (you can use the option several times).
The source of depencies are downloaded in a directory like "/home/lobianco/.cargo/...".
A good way to know is to have a look at the generated info file and see what the undesired paths.
FYI, there's an option -t html to output directly some html (and use -o for the output directory) to avoid genhtml (we'd like to have feedback on this option :)).

**Comment by lobianco** [comment]
@calixteman that did it! I could've sworn I tried that early on in my troubleshooting but I guess not. 

I'm only using genhtml as a stopgap until I start uploading my results to GitLab's CI. But good tip on the `-t html`.

Thank you for your help 🙂

**Comment by blaesus** [comment]
@lobianco Thanks for raising the questions.
I ended up brute-forcing enumeration of all unwanted dependencies like this:

```
zip -0 ccov.zip `find . \( -name "libMYPROJECT*.gc*" \) -print`;
grcov ccov.zip -t lcov \
  --ignore-dir *github.com* \
  --ignore-dir *libcore* \
  --ignore-dir *rustc* \
  --ignore-dir *liballoc* \
  > lcov.info
```

**Comment by mihaipop11** [comment]
--ignore "*cargo*"
