### ISSUE TITLE
Command-line option for parallel mode

### ISSUE THREAD

**Issue by zhihaoy** [mozilla/grcov#331]
See also https://docs.coveralls.io/api-reference

This is needed to setup build matrix.

**Comment by marco-c** [comment]
PR welcome, this should be an easy fix (in src/output.rs).

**Comment by M4rk9696** [comment]
Can I pick this up?

**Comment by M4rk9696** [comment]
I need to add a command-line option `parallel` that will be added to `output_coveralls`, right?

https://github.com/mozilla/grcov/blob/4c4a72ae4952c502d04c2974e46f5b14fde746da/src/output.rs#L337-L353
