### ISSUE TITLE
Add an option to only keep specific files (opposite of --ignore)

### ISSUE THREAD

**Issue by nesc1** [mozilla/grcov#332]
Hi, i use option --ignore <path> to remove paths that i don't want, but linux lcov version has an option to do the oposite:
```
lcov --extract <file> <path*> -o <new file>
```
Create a new lcov info file including information for only that path.

Is there a way to do the same with grcov?

Thanks for the attention and great work.

**Comment by marco-c** [comment]
Not right now, but I agree such an option would be useful (basically the opposite of --ignore, maybe we could call it --keep-only).
