### ISSUE TITLE
Fill out `git` key in Coveralls report

### ISSUE THREAD

**Issue by Minoru** [mozilla/grcov#362]
Coveralls docs [say](https://docs.coveralls.io/api-reference) that `git` can contain a lot more than grcov [currently supplies](https://github.com/mozilla/grcov/blob/b151dc60dacb091864be0735f7a369535623acd4/src/output.rs#L342-L347):

```json
{
    "git": {
        "head": {
            "id": "b31f08d07ae564b08237e5a336e478b24ccc4a65",
            "author_name": "Nick Merwin",
            "author_email": "...",
            "committer_name": "Nick Merwin",
            "committer_email": "...",
            "message": "version bump"
        },
        "branch": "master",
        "remotes": [
            {
                "name": "origin",
                "url": "git@github.com:lemurheavy/coveralls-ruby.git"
            }
        ]
    }
}
```

I'm not entirely sure, but I think the missing `author_name` etc. are the reason why grcov reports don't list this info: compare [this `grcov` report](https://coveralls.io/builds/27746263) with [this `cpp-coveralls` report](https://coveralls.io/builds/27040174).

I'm happy to add `--author-name`, `--author-email` etc., but won't it be too much? An alternative approach is to read this info directly from Git when `--commit-sha` is specified—but that means either adding `git2` crate as a dependency, or requiring `git` to be installed.

How should I proceed? (And should I proceed at all?)

**Comment by marco-c** [comment]
Thanks for reporting this. Relying on the `git` executable seems OK to me!

**Comment by Minoru** [comment]
Okay, I'm on it!
