### ISSUE TITLE
Oddity in what lines count towards coverage.

### ISSUE THREAD

**Issue by Nokel81** [mozilla/grcov#380]
I find it strange that the test functions are counted towards coverage percent. Would it be able to ignore this?

Some other things that I find strange which need to be covered but aren't always:

1. struct definitions (even if that variant is used)
2. trait definitions (even if a type which implements that trait is used through a trait typed variable)
3. comments (even if the following lines are executed)
4. Close braces (even if both branches are taken)
5. use statements

**Comment by Minoru** [comment]
> I find it strange that the test functions are counted towards coverage percent. Would it be able to ignore this?

I think you can put the tests into separate files, and ignore them by passing `--ignore` to grcov. That's be pretty inconvenient though:
1. keeping tests in a separate file makes it slightly harder to get to them;
2. keeping tests in a separate submodule means creating many more subdirectories;
3. I don't think `grcov` globs support `**`, so you'll have to `find -name` all the test files, and turn that list into a list of `--ignore` options.

I don't know much about the coverage format, but I don't think it marks which lines are tests and which ones aren't—so grcov probably can't tell them apart without your help.

**Comment by Nokel81** [comment]
Well it obviously can mark things as "not coverage" since items like `const` are just ignored. So it could just do that.

However, is this a better question to ask on the **rustc** side since that is where this information is generated?

**Comment by Minoru** [comment]
I believe the ignored lines are the ones for which the compiler didn't generate any code. This isn't something that grcov can do or influence—it can only display what the compiler told it, and what the runtime counted. So yeah, rustc repo might be a better place to discuss this.

**Comment by Nokel81** [comment]
Okay thanks, will close this one then.

**Comment by marco-c** [comment]
https://github.com/rust-lang/rust/issues/68703
