### ISSUE TITLE
Coverage report is blank when using data generated by cargo-cov

### ISSUE THREAD

**Issue by amyspark** [mozilla/grcov#390]
- cargo-cov version 0.0.5
- grcov version 0.5.9
- Rust toolchain 1.43.0-nightly (e02974078 2020-02-18)

I have a small app for which I test coverage via both documentation and integration tests. Usually, I'd just run in stable:
```
cargo cov test --doc
zip grcov.zip *.gc*
grcov ./grcov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" --ignore "cargo/*" -o lcov.info
genhtml lcov.info -o coverage
```
but `cargo cov` breaks when running integration tests, so instead I resorted to:
```
cargo cov test
grcov ./target/cov/build/gcda/ ./target/cov/build/gcno/ -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" --ignore "cargo/*" -o lcov.info
genhtml lcov.info -o coverage
```
The latter recognizes my source files, but it outputs 0% coverage for every file. `cargo cov report --open` yields a correct output.

**Comment by amyspark** [comment]
This issue is reproducible only in Linux when using the nightly toolchain, beta yields an incomplete report and outputs `[ERROR] Error in computing counters: File checksums do not match: 1628579742 != 2776909238 in lib`. 
All toolchain channels work in macOS.

**Comment by marco-c** [comment]
Could you upload the coverage artifacts?

**Comment by amyspark** [comment]
Here they go. 
[nightly.tar.gz](https://github.com/mozilla/grcov/files/4251954/nightly.tar.gz)
[beta.tar.gz](https://github.com/mozilla/grcov/files/4251956/beta.tar.gz)

**Comment by amyspark** [comment]
Ping, were you able to triage this @marco-c ?

**Comment by calixteman** [comment]
Probably some issue with `cargo cov` (we aren't the maintainers of this project).
I just `git clone https://framagit.org/amyspark/rattx.git` and ran the following commands:
```bash
CARGO_INCREMENTAL=0 RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads" cargo test
zip -0 ccov.zip `find . \( -name "rattx*.gc*" \) -print`;
grcov ccov.zip -s . -t html --llvm --branch --ignore-not-existing --ignore "/*" --ignore "cargo/*"
```
and I got a `html` dir containing some covered code in `src/commands` and in `src/extensions`.
Have look on this doc: https://github.com/mozilla/grcov#grcov-with-travis

**Comment by amyspark** [comment]
@calixteman , please note that I don't use `grcov` directly for the coverage report. 
Both `cargo cov` and `grcov` output valid data (as you demonstrated), the problem is I cannot use `lcov` to generate the report.

**Comment by calixteman** [comment]
The generated gcda (which contain the counter values) contain only zeros, it's why you get 0 coverage.
So the problem isn't on the `grcov` side but likely on `cargo cov` side.

**Comment by marco-c** [comment]
It seems like this isn't an issue in grcov.

**Comment by amyspark** [comment]
@marco-c , @calixteman , thanks for checking this out. I'd like to clearly dissent with you - this is certainly an issue with `grcov`.
[This job at Framagit](https://framagit.org/amyspark/rattx/-/jobs/756327) contains both the report generated by `cargo cov`, and the one generated by `lcov` with the output of `grcov`. Please notice that the lcov version is completely empty, whereas the cargo-cov version is not at all.

**Comment by marco-c** [comment]
I bet there is some mismatch in the paths.
Any reason why you don't directly use the grcov HTML output rather than converting to the LCOV format and using genhtml?

**Comment by amyspark** [comment]
@marco-c `grcov` doesn't print coverage rate info to console.
I use `genhtml` to output it to console, and then [Gitlab can capture it](https://docs.gitlab.com/ee/ci/pipelines/settings.html#test-coverage-parsing) with the regexp `^\s+lines\.+:\s+([\d.]+\%)\s+` for display in the job dashboard and coverage badge.

**Comment by marco-c** [comment]
We could add an option to grcov to print those stats at the end.
Could you also share with us the lcov.info output from grcov?

**Comment by amyspark** [comment]
Sure @marco-c ! [Here you go.](https://framagit.org/amyspark/rattx/-/jobs/968658/artifacts/browse)

**Comment by lclc** [comment]
I run into the same problem, but was able to solve it. I also use GitLab CI (and took some inspiration from @amyspark ci file, thanks for that). Maybe this helps:

I got it working with the following commands on OSX:
```
export RUSTC_BOOTSTRAP=1
export CARGO_INCREMENTAL=0
export RUSTDOCFLAGS="-Cpanic=abort"
export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
cargo build
cargo test
zip -0 ccov.zip `find . \( -name "projectname*.gc*" \) -print`;
grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" -o lcov.info;
genhtml lcov.info -o coverage
```

In my .gitlab-ci.yml I have the following code for adding the coverage % to GitLab and to push to codecov.io:

```
coverage:
  stage: coverage
  image: rustlang/rust:nightly-slim
  variables:
    CARGO_INCREMENTAL: 0
    RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
    RUSTDOCFLAGS: "-Cpanic=abort"
  script:
    - apt update
    - apt install -y lcov clang curl zip
    - cargo install grcov
    - cargo build
    - cargo test
    - zip -0 ccov.zip `find . \( -name "projectname*.gc*" \) -print`;
    - grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" -o lcov.info;
    - genhtml lcov.info -o coverage
    - bash <(curl -s https://codecov.io/bash) -f lcov.info;
  allow_failure: true
```

**Comment by amyspark** [comment]
@lclc thanks so much for your alternative! [It works!](https://framagit.org/amyspark/rattx/-/jobs/993386)

**Comment by marco-c** [comment]
I wonder what the problem was exactly.

**Comment by amyspark** [comment]
@marco-c I truly don't know. I had a look at `cargo-cov` again and [they set the same variables](https://github.com/kennytm/cov/blob/master/cargo-cov/src/shim.rs) as @lclc . Plus, their own `cargo cov report` works as expected.

**Comment by lclc** [comment]
If I remember it correctly I had to add cargo test, before that it was empty.


On a site note: The GitLab regex for test coverage I changed from lines to functions, because codecov uses functions.

`^\s+functions\.+:\s+([\d.]+\%)\s+`
