### ISSUE TITLE
Duplicate function detected

### ISSUE THREAD

**Issue by ethanabrooks** [mozilla/grcov#392]
I have the following project:
```
submission
├── Cargo.lock
├── Cargo.toml
├── src
│   └── lib.rs
└── tests
    └── unit.rs
```
`lib.rs` contains a simple function with three branches:
```rust
// submission/src/lib.rs
pub fn fib(n: i32) -> i32 {
    match n {
        0 => 1,
        1 => 1,
        _ => fib(n - 1) + fib(n - 2),
    }
}
```
My tests cover all the lines of code:
```rust
// submission/tests/unit.rs
use submission::fib;

#[test]
fn test0() {
    assert_eq!(fib(0), 1);
}

#[test]
fn test1() {
    assert_eq!(fib(1), 1);
}

#[test]
fn test2() {
    assert_eq!(fib(2), 2);
}
```
However when I run `genhtml` on the `grcov` output, it indicates that there are two functions, only one of which gets tested:
```
Reading data file ccov/lcov.info
Resolved relative source file path "src/lib.rs" with CWD to "/Users/ethan/autograder/autograder/submission/src/lib.rs".
Found 1 entries.
Found common filename prefix "/Users/ethan/autograder/autograder/submission"
Writing .css and .png files.
Generating output.
Processing file src/lib.rs
Writing directory view page.
Overall coverage rate:
  lines......: 100.0% (6 of 6 lines)
  functions..: 50.0% (1 of 2 functions)
```
Neither function is given a human-readable name:
![image](https://user-images.githubusercontent.com/10344742/76147576-b7d24780-606b-11ea-8f07-15646b34374f.png)
Moreover, both functions appear to refer to the same lines of code:
![image](https://user-images.githubusercontent.com/10344742/76147599-ecde9a00-606b-11ea-98da-f310f59df5fd.png)

The full set of commands to reproduce this bug (from the `submission/` directory) is:
```bash
mkdir ccov
export CARGO_INCREMENTAL=0
export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads"
cargo build
cargo test
zip -0 ccov/ccov.zip $(find . \( -name "submission*.gc*" \) -print)
grcov ccov/ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing  -o ccov/lcov.info
genhtml -o ccov --show-details --highlight --ignore-errors source --legend ccov/lcov.info
```

**Comment by calixteman** [comment]
Just after cargo test, just run `find . -name "*.gc*"` and you'll get something like:
```bash
./target/debug/deps/submission-2221ce36ef4c6136.gcda
./target/debug/deps/unit-97c13f783e91988c.gcno
./target/debug/deps/submission-6f67ef14de69480c.gcno
./target/debug/deps/unit-97c13f783e91988c.gcda
./target/debug/deps/submission-6f67ef14de69480c.gcda
```
As you can see there are 2 `submission-foo` and each of them bring a function `fib`.
I've no idea why `cargo` is doing that (probably related to the way to run tests).
Maybe file a bug: https://github.com/rust-lang/cargo
