### ISSUE TITLE
Confusion over branch coverage

### ISSUE THREAD

**Issue by ethanabrooks** [mozilla/grcov#393]
I have the following project:
```
submission
├── Cargo.lock
├── Cargo.toml
├── src
│   └── lib.rs
└── tests
    └── unit.rs
```
`lib.rs` contains a simple function with three branches:
```rust
// submission/src/lib.rs
pub fn fib(n: i32) -> i32 {
    match n {
        0 => 1,
        1 => 1,
        _ => fib(n - 1) + fib(n - 2),
    }
}
```
My tests cover all the lines of code:
```rust
// submission/tests/unit.rs
use submission::fib;

#[test]
fn test0() {
    assert_eq!(fib(0), 1);
}

#[test]
fn test1() {
    assert_eq!(fib(1), 1);
}

#[test]
fn test2() {
    assert_eq!(fib(2), 2);
}
```
When I look at the resulting `lcov.info` file, it looks like it identifies only one branch, but says that my tests hit three branches:
```bash
cat ../submission/ccov/lcov.info
TN:
SF:src/lib.rs
FN:1,_ZN10submission3fib17he3c740a03be88d3bE
FN:1,_ZN10submission3fib17h812108156555ad55E
FNDA:1,_ZN10submission3fib17he3c740a03be88d3bE
FNDA:0,_ZN10submission3fib17h812108156555ad55E
FNF:2
FNH:1
BRDA:3,0,0,1  # branch 0, associated with line 3
BRDA:3,0,1,1  # branch 1, associated with line 3
BRDA:3,0,2,1  # branch 2, associated with line 3
BRF:1  # branches found
BRH:3  # branches hit
DA:1,20
DA:2,20
DA:3,20
DA:4,8
DA:5,4
DA:7,20
LF:6
LH:6
end_of_record
```
Also, why are all three branches associated with the same line? Am I misinterpretting this output?

To reproduce, go the `submission/` directory and: 
```bash
mkdir ccov
export CARGO_INCREMENTAL=0
export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads"
cargo build
cargo test
zip -0 ccov/ccov.zip $(find . \( -name "submission*.gc*" \) -print)
grcov ccov/ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing  -o ccov/lcov.info
genhtml -o ccov --show-details --highlight --ignore-errors source --legend ccov/lcov.info
```

**Comment by calixteman** [comment]
I think you're making a confusion between branches and blocks:
 - you've 3 blocks at lines 4,5 & 6
 - you've 3 edges starting at line 3 and going to each block.
So I'd say that BRDA line number is the line where the edge comes from.
To be sure (the `lcov` doc is kinda unclear), I wrote this code in C (`gcc foo.c --coverage -oo && ./o`):
```c
int main() {
    int x = 0;
    int y;
    switch (x) {
    case 0:
        y = 1;
        break;
    case 1:
        y = 2;
        break;
    case 2:
        y = 3;
        break;
    }

    return y;
}
```
and the resulting `.info` (`lcov --capture --directory . -o foo.info --rc lcov_branch_coverage=1`) contains:
```lcov
TN:
SF:/tmp/foo.c
FN:1,main
FNDA:1,main
DA:1,1
DA:2,1
DA:4,1
BRDA:4,0,0,1
BRDA:4,0,1,0
BRDA:4,0,2,0
BRDA:4,0,3,0
DA:5,1
DA:6,1
DA:7,1
DA:8,0
DA:9,0
DA:10,0
DA:11,0
DA:12,0
DA:13,0
DA:16,1
end_of_record
```
So I'd say that my hypothesis was the good one.

**Comment by ethanabrooks** [comment]
What do you make of BRF--number of branches found, according to the lcov docs? Shouldn't branches hit (BRH) be less than or equal to branches found?

**Comment by calixteman** [comment]
My bad, I read your comment to quickly.
Yes, there is something strange with BRF, the doc says:
`BRF:<number of branches found>`
so maybe it should be 3 here.
