### ISSUE TITLE
Inconsistent coverage report

### ISSUE THREAD

**Issue by lmammino** [mozilla/grcov#401]
Hello, here a Rust noob, so please excuse if this issue will end up being just the result of some stupid mistake on my side.

Anyway, I just added `grcov` to the CI of my [first Rust project](https://github.com/lmammino/jwtinfo).

The issue I am seeing is that some line are reported as not covered when they obviously are (too me).

Take this example here: https://codecov.io/gh/lmammino/jwtinfo/src/feature%2Fcoverage-reports/src/jwt/mod.rs

[Lines 25-33](https://codecov.io/gh/lmammino/jwtinfo/src/feature%2Fcoverage-reports/src/jwt/mod.rs#L25...33) are considered not covered (`new` function for the struct `Token`), but at [line 141](https://codecov.io/gh/lmammino/jwtinfo/src/feature%2Fcoverage-reports/src/jwt/mod.rs#L141) I am explicitly calling that function and this line is considered covered.

Am I missing something or is this an actual issue, either with my config or with `grcov` itself?

Thanks

(Ref https://github.com/lmammino/jwtinfo/pull/17 to see my config)

**Comment by lmammino** [comment]
Managed to run tests using [`tarpaulin`](https://github.com/xd009642/tarpaulin) and I get way better results. See the attached report for comparison. 

[tarpaulin-report.html.zip](https://github.com/mozilla/grcov/files/4377899/tarpaulin-report.html.zip)

Tarpaulin is a lot more complicated to set up and it does not provide reporting for branches and calls count (as far as I can tell), so I'd love to be able to stick to `grcov`.

**Comment by calixteman** [comment]
Just adding `#[inline(never)]` on `Token::new` definition is enough to show that this function is covered.
So for me it isn't a bug in grcov but in rust compiler.
Normally the compiler option `-Cinline-threshold=0` should disable inlining on such a function.

**Comment by calixteman** [comment]
FYI, I filed a bug:
https://github.com/rust-lang/rust/issues/70426

**Comment by lmammino** [comment]
Thanks a lot @calixteman! I will follow along on your issue!
