### ISSUE TITLE
cargo cannot upgrade from grcov 0.5.9 -> 0.5.10

### ISSUE THREAD

**Issue by U007D** [mozilla/grcov#405]
upgrading with `topgrade` or just a `cargo install grcov` fails with
```bash
...
  = note: /usr/bin/ld: cannot find -ltcmalloc
          collect2: error: ld returned 1 exit status


error: aborting due to previous error

error: failed to compile `grcov v0.5.10`, intermediate artifacts can be found at `/tmp/cargo-installFxiBHk`

Caused by:
  could not compile `grcov`.
```
Is this expected?  Or is `tcmalloc` expected to be installed at some location?
Pop_OS!/Ubuntu

**Comment by jcdickinson** [comment]
Seems like #403 will resolve this, after #402 introduced it.

More context: this breaks anybody using https://github.com/actions-rs/grcov in the absence of a workaround.

**Comment by calixteman** [comment]
I'll try fix that today, sorry for the inconvenience.
Anyway a workaround to build and run it is to install the package `libgoogle-perftools4-dev` (debian/ubuntu) to compile grcov.
And it induces a runtime dependency on `libtcmalloc.so` which is in package `libgoogle-perftools4`.

**Comment by calixteman** [comment]
Anyway, I just made a patch make tcmalloc optional.

**Comment by marco-c** [comment]
I've released 0.5.11.

**Comment by U007D** [comment]
I just upgraded successfully from 0.5.9->0.5.12 where yesterday the same failed.
I'm not sure what 0.5.11 had to do with it, but thanks!

**Comment by RCasatta** [comment]
is it possible that bundled binaries still needs tcmalloc available at runtime, my travis job contains (it just run so I think it's using 0.5.12)

```
curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -
```
fails with
```
./grcov: error while loading shared libraries: libtcmalloc.so.4: cannot open shared object file: No such file or directory
```

I am temporarily switching back to 0.5.9

**Comment by marco-c** [comment]
The release in GitHub releases depends on tcmalloc, yes. We could possibly avoid that.
Why are you not using Cargo?

**Comment by RCasatta** [comment]
To be honest I just followed grcov README https://github.com/mozilla/grcov#grcov-with-travis

I changed my .travis.yml with cargo install and it works with 0.5.12 but the job it's taking about 2 minutes more than downloading binaries

**Comment by kngwyu** [comment]
@RCasatta 
I encountered the same problem and resolved it by
```yaml
addons:
  apt:
    packages:
      - libgoogle-perftools-dev
```

**Comment by marco-c** [comment]
We are releasing a new version soon which removes the tcmalloc dependency (you will have a "normal" release without tcmalloc and a release with tcmalloc).
