### ISSUE TITLE
Ignore lines under "test" directive

### ISSUE THREAD

**Issue by j4qfrost** [mozilla/grcov#424]
Is there a way to ignore code that is configured under #[cfg(test)]? I currently write tests that are placed inside the source files for convenience, and it's a pain to see the line and function percentages skewed because coverage is expected for the tests as well.

**Comment by Minoru** [comment]
Try putting them in separate files and ignoring with `--ignore`. See https://github.com/mozilla/grcov/issues/380 for previous discussion on this.

**Comment by j4qfrost** [comment]
I know I can do that, but there's a lot of convenience with being able to access the private members variables for checking that a struct actually gets mutated. The organization is also more appealing to me when thinking about some code and going immediately to the tests.

**Comment by j4qfrost** [comment]
Read the thread a bit closer. I guess I'll close this. Thanks.
