### ISSUE TITLE
README.md: Command line example does not work with rustc nightly 2020-04-30

### ISSUE THREAD

**Issue by gifnksm** [mozilla/grcov#427]
The following command line option no longer works with rustc nightly due to the removal of the `-Zno-landing-pads` option (rust-lang/rust#70175)

```
export CARGO_INCREMENTAL=0
export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads"
```

**Comment by wusyong** [comment]
So is it safe if we just remove `no-landing-pads`? Or we should also add `panic=abour`?

**Comment by kngwyu** [comment]
Hey guys, I also encountered this issue and removed `no-landing-pads`, resulting in decreased coverage from 58% to 38%.
https://codecov.io/gh/PyO3/pyo3/branch/master/commits?from=2020-04-28%2000%3A00%3A00&to=2020-05-03%2000%3A00%3A00

Any idea?

**Comment by calixteman** [comment]
> Hey guys, I also encountered this issue and removed `no-landing-pads`, resulting in decreased coverage(from 58% to 38%).
> https://codecov.io/gh/PyO3/pyo3/branch/master/commits?from=2020-04-28%2000%3A00%3A00&to=2020-05-03%2000%3A00%3A00
> 
> Any idea?

Quite strange..., could you file a bug and attached a lcov.info file (if possible the one generated in your CI) ?

**Comment by calixteman** [comment]
Yep it's safe to remove `no-landing-pads`.
The only problem that we'll some accuracy...
A partial workaround could be to use the new option `--exec-line` with pattern `"^[ \t]*\}[ \t]*$"` to not count lines with only a closing brace (most of the time clean up stuff on stack unwinding is associated with the debug info of the closing element).

**Comment by calixteman** [comment]
I just read the rustc patch and it seems that `-Cpanic=abort` is (for now) just a renaming.
If I missed something please tell me but using this option should be equivalent to no-landing-pads.

**Comment by calixteman** [comment]
I managed to run tests for pyo3 in using `-Cpanic=abort -Zpanic_abort_tests` in `RUSTFLAGS`.
The doc tests were failing with that so adding an extra `RUSTDOCFLAGS="-Cpanic=abort"` fixes failures.

**Comment by rivy** [comment]
So, when fixing the problem by dropping `-Zno-landing-pads` and adding `-Cpanic=abort -Zpanic_abort_tests` to `RUSTFLAGS` and setting `RUSTDOCFLAGS="-Cpanic=abort"`, does coverage drop?

Currently, to avoid problems or code coverage drops, my workaround for [uutils/coreutils](https://github.com/uutils/coreutils) is pinning the rust version to the last working toolchain (`nightly-2020-04-29`) for code coverage.

**Comment by calixteman** [comment]
@rivy please make a try.
I made the change this afternoon for an other project:
https://codecov.io/gh/calixteman/dump_syms/commits
and it's ok.

**Comment by rivy** [comment]
@calixteman , Ok, will do ...

**Comment by kngwyu** [comment]
@calixteman 
> I managed to run tests for pyo3 in using -Cpanic=abort -Zpanic_abort_tests in RUSTFLAGS.
The doc tests were failing with that so adding an extra RUSTDOCFLAGS="-Cpanic=abort" fixes failures.

Great, thank you for investigating that!
