### ISSUE TITLE
Specify in the documentation that Nightly (or RUSTC_BOOTSTRAP) are required for `Z` options

### ISSUE THREAD

**Issue by timgabets** [mozilla/grcov#433]
Hi there, 

I've tried to use grcov to generate the coverage report for my project (I'm using stable Rust)

I've set the environment variables as it's written in README: 
```console
export CARGO_INCREMENTAL=0
export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
export RUSTDOCFLAGS="-Cpanic=abort"
```
…but when trying to build my code I see this:
```console
$ rustc --version
rustc 1.41.0
$ cargo build
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names -Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit code: 1)
--- stderr
error: the option `Z` is only accepted on the nightly compiler`
```
I've tried to remove all the Z options, and build my project again, but as I see, there is not .gcno files produced in target/debug/deps/

The question is - is it possible to make grcov work with the stable Rust, or it's nightly-only feature?

**Comment by calixteman** [comment]
Yep normally it's a nightly feature.
But you should be able to use stable with env: `RUSTC_BOOTSTRAP=1`

**Comment by e00E** [comment]
This should be explained in the Readme as the current text doesn't mention nightly so it is confusing that the instructions don't work.

**Comment by marco-c** [comment]
It's a bit out of scope, as it's a Rust thing, but I'm OK with adding this to the README to avoid confusion.

**Comment by BenChand** [comment]
Please mention this in the Readme!
