### ISSUE TITLE
Output a readable error message when the selected output file is not a file

### ISSUE THREAD

**Issue by cdbrkfxrpt** [mozilla/grcov#435]
when i run the example from README with the lcov flag (which is the default), the following happens:
```
» grcov ./target/debug/ -s . --llvm --branch --ignore-not-existing -o ./target/debug/coverage/
10:14:36 [ERROR] A panic occurred at /home/flrn/.cargo/registry/src/github.com-1ecc6299db9ec823/grcov-0.5.13/src/output.rs:24: called `Result::unwrap()` on an `Err` value: Os { code: 21, kind: Other, message: "Is a directory" }
```
i get the same output when i specify `-t lcov` explicitly. it runs fine with the `-t html` flag

**Comment by marco-c** [comment]
It's because the output file should be a file, you are instead passing a directory. I guess we can use a better error message here.

**Comment by cdbrkfxrpt** [comment]
thanks, it didn't occur to me trying to specify the lcov.info as output - i thought the behaviour would be the same for html and lcov both. perhaps there is an ergonomic improvement to be had here, too.
