### ISSUE TITLE
Support showing branch coverage in the html report

### ISSUE THREAD

**Issue by remidargent** [mozilla/grcov#445]
I used the options `--branch` and `-t html` to generate the html report but the branch information is missing from the report.

There is only **Lines** and **Functions** information.

Note: the branch coverage is available if exporting to lcov, then using genhtml.

The version I use is grcov 0.5.15

**Comment by marco-c** [comment]
Thanks, that'd be a nice feature to add, PRs welcome!

**Comment by calixteman** [comment]
The code for html output is here: https://github.com/mozilla/grcov/blob/master/src/html.rs
