### ISSUE TITLE
Why does this example have only 75% function coverage?

### ISSUE THREAD

**Issue by Ryan1729** [mozilla/grcov#454]
If I follow the instructions in the README to generate a coverage report on the following code then I get 100% line coverage as expected, but only 75% function coverage.
```rust
fn main() {
    println!("Hello, world!");
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn it_works() {
        main();
    }
}
```
Specifically it says 3 functions were hit out of a total of 4. Why does that happen? What function is not being hit?

I'm guessing that rust's thin runtime exports a function that is not being run here. If that is the case, then is there a way to ignore and/or "test" that function?

**Comment by marco-c** [comment]
I'm pretty sure this is the same as #476.

You could try source-based coverage, I've recently added support for it in grcov (version 0.6.0). Short explanation at https://marco-c.github.io/2020/11/24/rust-source-based-code-coverage.html, docs at https://github.com/mozilla/grcov#example-how-to-generate-source-based-coverage-for-a-rust-project, full example at https://github.com/marco-c/rust-code-coverage-sample.

If you do try, please report back on the results ;)
