### ISSUE TITLE
Error in computing counters: Unexpected version: R37A what does it mean?

### ISSUE THREAD

**Issue by DashYang** [mozilla/grcov#471]
after compiling and executing test
I run like grcov ./ -s . -t lcov --llvm --branch --ignore-not-existing  -o app.info
but got 
09:11:35 [ERROR] Error in computing counters: Unexpected version: R37A in XXXXXXX
what does it mean?

**Comment by marco-c** [comment]
Sorry for the delay @DashYang. What were you trying to parse with grcov? Was it coverage output from a C/C++ binary? What compiler did you use to build the binary?

**Comment by marco-c** [comment]
Closing for lack of response, but feel free to reopen if you have time to reply.
