### ISSUE TITLE
Add a clear error message when output fails if directory doesn't exist

### ISSUE THREAD

**Issue by GrayStrider** [mozilla/grcov#481]
```
panic <...> grcov-0.5.15\src\output.rs:33: 
Cannot create the file .\coverage\lcov.info to dump coverage data
```
I'll create directory manually for now

**Comment by GroteGnoom** [comment]
@marco-c Are you sure you want this changed? This seems like normal behavior. This prevents trouble with misspellings. Maybe it should add that the directory does not exist in the error info?

**Comment by marco-c** [comment]
@GroteGnoom you're right, it's better to simply improve the error message.

**Comment by mariot** [comment]
Hello! I can take on this feature if you want.
Just to be sure, the goal is to change the error message to say that the directory doesn't exist?
So the program would still panic but just with a clearer error message?
Thanks

**Comment by marco-c** [comment]
@mariot yes, thanks!
