### ISSUE TITLE
Coverage misses on derive and struct fields

### ISSUE THREAD

**Issue by kennetpostigo** [mozilla/grcov#501]
I've been using `grcov` recently and noticed that I was getting coverage misses here:
![image](https://user-images.githubusercontent.com/8888991/97601649-c72e4880-19e0-11eb-93a8-08014a5471dd.png)

I was hoping other folks ran into this and if there was any solution to getting `grcov` to pick up coverage an on `derive` and also my struct.

If there are any solutions or work arounds that folks have setup that would be awesome! I'm not sure if this issue has been reported or not, but hopefully this is useful information to the maintainers of `grcov`

**Comment by sylvestre** [comment]
How it started:
https://twitter.com/kennetpostigo/status/1321849654183632896

**Comment by marco-c** [comment]
Unfortunately this is a known problem, but there is a partial workaround that you could use (see #476 and #416).
