### ISSUE TITLE
Project compile fails when trying to run tests for coverage

### ISSUE THREAD

**Issue by Sibz** [mozilla/grcov#502]
Originally opened an issue with intellj rust plugin as it was failing to run code coverage after following their setup instructions and using the integrated 'run tests with coverage' button.

They have checked and found it to be an issue on the grcov side.

Full details included steps to reproduce in that issue here:
https://github.com/intellij-rust/intellij-rust/issues/6325

**Comment by marco-c** [comment]
If it is a compilation error, it is a bug in Rust itself, rather than grcov. grcov runs *after* the program is compiled and *after* the tests run.
Can you open an issue on the Rust repository?
