### ISSUE TITLE
Use the new Rust code coverage instrumentation for improved coverage

### ISSUE THREAD

**Issue by zbraniecki** [mozilla/grcov#509]
Rust just merged code coverage instrumentation that I believe would vastly improve the accuracy of results - https://www.reddit.com/r/rust/comments/jrlnfk/llvm_code_coverage_instrumentation_pr_merged/

**Comment by marco-c** [comment]
\o/

We definitely need to add support for it.

**Comment by marco-c** [comment]
This is now supported, short explanation at https://marco-c.github.io/2020/11/24/rust-source-based-code-coverage.html, docs at https://github.com/mozilla/grcov#example-how-to-generate-source-based-coverage-for-a-rust-project, full example at https://github.com/marco-c/rust-code-coverage-sample.
