### ISSUE TITLE
Handle overflows in counters

### ISSUE THREAD

**Issue by marco-c** [mozilla/grcov#525]
Revert 155c73f05c67f173c75946b07e22b9d53f65d647, and correctly handle overflows in counters (apparently there are lines which are hit many many times).

**Comment by marco-c** [comment]
STR:
```
export RUSTFLAGS="-Zinstrument-coverage"
LLVM_PROFILE_FILE="grcov-%p-%m.profraw" cargo test
cargo run -- `find . \( -name "grcov-*.profraw" \) -print` --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
```

**Comment by marco-c** [comment]
This shows something is wrong with counters:
```
export RUSTFLAGS="-Zinstrument-coverage"
LLVM_PROFILE_FILE="grcov-%p-%m.profraw" cargo test --lib path_rewriting
rust-profdata merge -sparse `find . \( -name "grcov-*.profraw" \) -print` -o grcov.profdata
rust-cov export target/debug/deps/grcov-13778df2ccd171b3 --instr-profile grcov.profdata --format lcov
```
N.B.: `grcov-13778df2ccd171b3` should be the binary that is run as part of cargo test.

You will see some lines which have unexpectedly high counts, such as `DA:119,18446744073709551615`.

**Comment by calixteman** [comment]
The number `18446744073709551615` is `(1 << 64 - 1)` so it looks like it's a `int64(-1)` casted into a uint64.
