### ISSUE TITLE
Source-based coverage doesn't support link-dead-code?

### ISSUE THREAD

**Issue by redtankd** [mozilla/grcov#531]
I followed these steps:

```
rustup component add llvm-tools-preview
set -x RUSTFLAGS "-Zinstrument-coverage"
cargo clean
cd code-coverage/     # my crate is in a cargo workspace
cargo build --verbose
LLVM_PROFILE_FILE="your_name-%p-%m.profraw" cargo test --verbose
grcov . --binary-path ./target/debug/ -s . -t html --branch --ignore-not-existing --ignore "/*"
```

And I got this result

<img width="718" alt="image" src="https://user-images.githubusercontent.com/6535864/100705063-8eb7cb00-33e1-11eb-8727-698ad23bd6a9.png">

The function `get_id(&self)` isn't count in the total. I added `-Clink-dead-code` to `RUSTFLAGS`, but it didn't work still.

gcov-based coverage is good.

**Comment by marco-c** [comment]
@redtankd same result if you add `-Copt-level=0`?

**Comment by redtankd** [comment]
yes

**Comment by marco-c** [comment]
@redtankd could you file an issue on https://github.com/rust-lang/rust?

**Comment by redtankd** [comment]
Source-based coverage is not stable enough now. I close this issue now. Thank you.
