### ISSUE TITLE
Variable/incorrect coverage metrics depending on rustup default

### ISSUE THREAD

**Issue by marcbrevoort-cyberhive** [mozilla/grcov#545]
This relates to grcov 0.6.1.

When running grcov this does output metrics, however they seem off.

For instance, the reported degree of function-coverage may be (exactly) 50% for a file that has 100% of its lines covered, or the line count of a file shows more lines than the file actually contains.

When showing the visual representation of coverage of the actual files, however, the covered/uncovered lines in the files appear to be colour coded more or less sensibly. 

I'd half expect this to be a result of the rust compiler running two passes and lines being counted twice. 
Once metrics have been collected, re-running grcov following `rustup default stable` appears to mostly correct the line counts in the report:
```
mrjb@mrjb-Inspiron-7501$ ./build/coverage
Running grcov as mrjb
Coverage percentage is 33

mrjb@mrjb-Inspiron-7501$ rustup default stable
info: using existing install for 'stable-x86_64-unknown-linux-gnu'
info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.47.0 (18bf6b4f0 2020-10-07)

mrjb@mrjb-Inspiron-7501$ ./build/coverage
Running grcov as mrjb
12:54:02 [ERROR] Error while executing llvm tools: Failed to execute "/home/mrjb/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-profdata" "merge" "-sparse" "/tmp/.tmpPUONq7/coverage
[...snipsnip...]
Coverage percentage is 53
```
likewise when switching back to `rustup default nightly` again on the same collected coverage data set, `grcov` once again reports a coverage of 33% vs 53% when running on stable.

In both cases the script invokes `grcov` is invoked with 

```grcov . --binary-path $APP_ROOT/target/debug/ -s ./src -t html --llvm --branch --ignore-not-existing -o $APP_ROOT/coverage/```

 however the function count is still off.

**Comment by marco-c** [comment]
You should probably avoid running grcov with a different Rust toolchain than what you used to build.
Do you still see differences if you build your project with stable and run grcov with stable vs build your project with nightly and run grcov with nightly?

> the line count of a file shows more lines than the file actually contains

Did you look at the actual line numbers? What lines don't actually exist in the file?

How are you computing the percentages?

I wonder if you are counting lines from libraries too, you could exclude them from the report by using `--ignore "/*"`.

**Comment by marcbrevoort-cyberhive** [comment]
> Do you still see differences if you build your project with stable and run grcov with stable vs build your project with nightly and run grcov with nightly?

`cargo build` only collects statistics under nightly, as this requires using `-Z` flags such as `-Zprofile -Zpanic_abort_tests -Zinstrument-coverage` which are unavailable in stable.

I have now run grcov with `--ignore "/*"` but the results, while significantly useful for TDD, are still a bit spotty - as shown below.
Strictly running on the nightly toolchain, this is some example HTML output:

```
<!DOCTYPE html>
<html lang="en-us">
<head>
<title>Grcov report &mdash;auth_dummy.rs</title>
<link rel="stylesheet" href="grcov.css">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>
<body>
<div class="header">
<div class="view">
<div class="viewRow"><span class="viewItem">Current view:</span><span class="viewValue"><a href="index.html">top level</a> - <a href="index.html"></a> - auth_dummy.rs</span></div>
<div class="viewRow"><span class="viewItem">Date:</span><span class="viewValue">2020-12-17 11:25:04</span></div>
</div>
<div class="stats">
<div class="statsRow"><span></span><span class="statsHit">Hit</span><span class="statsTotal">Total</span><span class="statsCoverage">Coverage</span></div>
<div class="statsRow"><span class="statsLine">Lines</span><span class="linesHit">8</span><span class="linesTotal">9</span><span class="linesPercentage lineMed">88.9 %</span></div>
<div class="statsRow"><span class="statsFun">Functions</span><span class="funsHit">1</span><span class="funsTotal">2</span><span class="funsPercentage funLow">50.0 %</span></div>
<div class="statsRow"><span class="statsBranches">Branches</span><span class="branchesHit">3</span><span class="branchesTotal">4</span><span class="branchesPercentage branchMed">75.0 %</span></div>
</div>
</div>
<div class="sourceCode">
<div class="line"><span id="1" class="lineNum"><a href="#1">1</a></span><span class="counterCov">1</span><span class="lineCov">use crate::errors::Exception;</span></div>
<div class="line"><span id="2" class="lineNum"><a href="#2">2</a></span><span class="counterUnCov"></span><span class="lineUnCov">use crate::network::Header;</span></div>
<div class="line"><span id="3" class="lineNum"><a href="#3">3</a></span><span class="counterCov">2</span><span class="lineCov">pub fn authenticate(</span></div>
<div class="line"><span id="4" class="lineNum"><a href="#4">4</a></span><span class="counterUnCov"></span><span class="lineUnCov">    username: &amp;String,</span></div>
<div class="line"><span id="5" class="lineNum"><a href="#5">5</a></span><span class="counterUnCov"></span><span class="lineUnCov">    _server: &amp;String,</span></div>
<div class="line"><span id="6" class="lineNum"><a href="#6">6</a></span><span class="counterUnCov"></span><span class="lineUnCov">    _interactive: bool,</span></div>
<div class="line"><span id="7" class="lineNum"><a href="#7">7</a></span><span class="counterUnCov"></span><span class="lineUnCov">) -&gt; Result&lt;(String, Vec&lt;Header&gt;), Exception&gt; {</span></div>
<div class="line"><span id="8" class="lineNum"><a href="#8">8</a></span><span class="counterCov">4</span><span class="lineCov">    println!(&quot;======DUMMY AUTHENTICATION======&quot;);</span></div>
<div class="line"><span id="9" class="lineNum"><a href="#9">9</a></span><span class="counterCov">4</span><span class="lineCov">    if &amp;username[..6] == &quot;alice@&quot; {</span></div>
<div class="line"><span id="10" class="lineNum"><a href="#10">10</a></span><span class="counterCov">2</span><span class="lineCov">        let resultheaders = Vec::&lt;Header&gt;::new();</span></div>
<div class="line"><span id="11" class="lineNum"><a href="#11">11</a></span><span class="counterCov">2</span><span class="lineCov">        return Ok((String::from(&quot;OK&quot;), resultheaders));</span></div>
<div class="line"><span id="12" class="lineNum"><a href="#12">12</a></span><span class="counterNoCov">0</span><span class="lineNoCov">    }</span></div>
<div class="line"><span id="13" class="lineNum"><a href="#13">13</a></span><span class="counterCov">2</span><span class="lineCov">    return Err(Exception::AuthenticationFailure);</span></div>
<div class="line"><span id="14" class="lineNum"><a href="#14">14</a></span><span class="counterCov">4</span><span class="lineCov">}</span></div>
</div>
</body>
</html>
```

| How are you computing the percentages?

I'm leaving percentage calculation to grcov. For visualising them I output to HTML. In the example above, strictly running on nightly, in a file that has all lines covered, it would follow that 100% of the functions in that file are covered, yet in that scenario the HTML output for grcov only shows 50% function coverage and 88.9 % code coverage (for some reason the closing curly bracket of the `if` statement is not deemed covered even though the code inside the `if` statement is).

**Comment by marco-c** [comment]
> `cargo build` only collects statistics under nightly, as this requires using `-Z` flags such as `-Zprofile -Zpanic_abort_tests -Zinstrument-coverage` which are unavailable in stable.

You can use those flags in stable by setting `RUSTC_BOOTSTRAP=1`.

> I have now run grcov with `--ignore "/*"` but the results, while significantly useful for TDD, are still a bit spotty - as shown below.
> 
> 
> | How are you computing the percentages?
> 
> I'm leaving percentage calculation to grcov. For visualising them I output to HTML. In the example above, strictly running on nightly, in a file that has all lines covered, it would follow that 100% of the functions in that file are covered, yet in that scenario the HTML output for grcov only shows 50% function coverage and 88.9 % code coverage (for some reason the closing curly bracket of the `if` statement is not deemed covered even though the code inside the `if` statement is).

This is partly expected, there are some things that are marked as uncovered (see #476 and all the other issues referenced in there).

You might have better luck on this front by using source-based code coverage (see https://github.com/mozilla/grcov/issues/476#issuecomment-732817417).
