### ISSUE TITLE
Support new gcov intermediate format from GCC 8

### ISSUE THREAD

**Issue by marco-c** [mozilla/grcov#55]
Changes in GCC 8:
https://github.com/gcc-mirror/gcc/commit/a82502ddf807cdd25fe04879390310727156ab42
https://github.com/gcc-mirror/gcc/commit/3cf7fddf54b5160e83236f1b9b3129e2a3a417c6

**Comment by Juniar-II** [comment]
Can you explain a little more about "GCOV support for an Intermediate format" and what this means?
How do you run this two codes gcc-mirror/gcc@a82502d, gcc-mirror/gcc@3cf7fdd?
And does these code require other dependencies files to execute?

**Comment by marco-c** [comment]
> Can you explain a little more about "GCOV support for an Intermediate format" and what this means?

This is a good first bug, but it requires a bit of research first. Have you tried looking it up online? Do you know what GCOV is?

> How do you run this two codes gcc-mirror/gcc@a82502d, gcc-mirror/gcc@3cf7fdd?
And does these code require other dependencies files to execute?

We don't have to run that, they are just patches showing what changed.

**Comment by marco-c** [comment]
@Juniar-II what you are describing is unrelated to this issue. This issue is just about adding support for parsing the new GCOV intermediate format.

**Comment by marxin** [comment]
For GCC 9.1 I'm planning to come up with JSON format of the intermediate format.
Maybe you'll be interested more in the format:
https://gcc.gnu.org/ml/gcc-patches/2018-09/msg01628.html

**Comment by marco-c** [comment]
Sounds great to me! Much less chance of breakages.

Looks like we were the only ones using the GCC intermediate format :smile:

**Comment by marco-c** [comment]
Will one JSON per source file be generated, or one JSON per compilation unit? The second is the current behavior of the intermediate format, and would be better for us.

**Comment by marxin** [comment]
> Sounds great to me! Much less chance of breakages.

Yes, it's more standard format than a custom one.

> 
> Looks like we were the only ones using the GCC intermediate format

Looks so, lcov is missing the capability:
https://github.com/linux-test-project/lcov/issues/43

Similarly for gcovr:
https://github.com/gcovr/gcovr/issues/282

**Comment by marxin** [comment]
> Will one JSON per source file be generated, or one JSON per compilation unit? The second is the current behavior of the intermediate format, and would be better for us.

Same as for current -i option: one intermediate file per compilation unit.
I'm also planning to make the JSON files gzipped as they can be quite big.
File example for tramp3d:
https://users.suse.com/~mliska/tmp/tramp.json

**Comment by marxin** [comment]
Note that the format change has landed into GCC's trunk and will be part of next release (9.1).

**Comment by marco-c** [comment]
We support GCC 9+, we won't support GCC 8.
