### ISSUE TITLE
floating point type error with gcov v9.3.0 

### ISSUE THREAD

**Issue by wideglide** [mozilla/grcov#570]
I'm geting a floating point error with grcov v0.7.1 and gcc/gcov version 9.3.0 on Ubuntu 20.04.

```shell
$ /usr/local/bin/grcov --branch -o outputs/cov/gcov/coverage.info gcov
22:38:25 [ERROR] A panic occurred at src/parser.rs:371: called `Result::unwrap()` on an `Err` value: Error("invalid type: floating point `7809720`, expected u64", line: 1, column: 84)
22:38:25 [ERROR] A panic occurred at src/parser.rs:371: called `Result::unwrap()` on an `Err` value: Error("invalid type: floating point `1864090`, expected u64", line: 1, column: 24437)
```

**Comment by marco-c** [comment]
What is `gcov` in your cmd line? Is it the `gcov` executable from GCC?
You shouldn't pass it to grcov, you should instead pass the paths to your coverage artifacts.

**Comment by wideglide** [comment]
`gcov` is a directory with the source files and coverage artifacts.

**Comment by marco-c** [comment]
@wideglide can you try running grcov on one artifact at a time? This way you can identify which one is breaking and upload it here.

Can you try with GCC 8 or GCC 10, to confirm it's restricted to GCC 9?
