### ISSUE TITLE
No builds for release 0.8.0

### ISSUE THREAD

**Issue by lu-zero** [mozilla/grcov#605]
Seems that the CI action did not trigger ?

**Comment by marco-c** [comment]
Yeah, the Travis deploy failed: https://travis-ci.org/github/mozilla/grcov/jobs/767864686. Probably the token expired or something like that.
We should really switch to Taskcluster (#135), we have more control there and travis-ci.org will be shutting down in several weeks anyway...

**Comment by marco-c** [comment]
I've done it manually now (I've only uploaded Linux binaries though).
