### ISSUE TITLE
Generate coverage badges for use in readmes

### ISSUE THREAD

**Issue by dnaka91** [mozilla/grcov#616]
First of all this tool is really great thanks for all the great work 🎉.

Currently I generate HTML and LCOV output, one for local insection, the other goes to codecov.io.

That works all nice, but I don't really need codecov.io as grcov can generate this nice HTML page already so instead of uploading the LCOV files I plan to instead host the generated pages on GitHub Pages instead and link that in the readme.

Now the only missing piece for that would be a nice badge that shows the current coverage in the readme. As the coverage would be self hosted I can't use shields.io to query the current coverage percentage.

Therefore, it would be great to have the SVGs for a few coverage badges directly generated by grcov together with the current HTML output. It would probably be fine to take the badge generation logic from shields.io directly as it's under the `CC0-1.0` license.

I would be happy to implement this myself, just wanted to hear about the general interest of generating badges first.

**Comment by marco-c** [comment]
@dnaka91 this sounds like a very nice idea! It'd be great for projects that don't want to rely on third-party services.
I wonder if we can't rely on the "Dynamic" or the "Endpoint" method (e.g. https://shields.io/endpoint) instead of generating SVGs.

**Comment by dnaka91** [comment]
Oh, I didn't know about that endpoint yet. Very nice feature. I built both now, the a JSON file with the format that shields.io needs and self-generated badges and will open the PR in a minute.
