### ISSUE TITLE
Feature Request: Add a codecov output format

### ISSUE THREAD

**Issue by maboesanman** [mozilla/grcov#632]
Codecov supports partial lines in its own format, but when using the coveralls format to upload to codecov, this granularity is lost.

It should be possible to determine for a line with multiple branches present how many of those branches were hit, which is exactly what the format captures.

specification of the format:
https://docs.codecov.io/docs/codecov-custom-coverage-format

**Comment by maboesanman** [comment]
I can try to make a PR for this but I wanted to check that this would be a welcome addition first

**Comment by marco-c** [comment]
@maboesanman I'd be happy to accept a PR!

**Comment by maboesanman** [comment]
@marco-c Do you have any information on the format of the `CovResult` struct?

Copied here for reference:
```rust
pub struct CovResult {
    pub lines: BTreeMap<u32, u64>,
    pub branches: BTreeMap<u32, Vec<bool>>,
    pub functions: FunctionMap,
}
```

The `lines` field seems strait forward (map from line numbers to counts)

I'm unclear how exactly`BTreeMap<u32, Vec<bool>>` models branch coverage. Is the `u32` key a line number or some sort of binary offset? Is it defined in some llvm tooling documentation or is it original to this crate?

**Comment by marco-c** [comment]
The struct is original to this crate.
The `branches` is something like: LINE NUMBER -> [BRANCH_1, BRANCH_2, BRANCH_3] (where BRANCH_X is `true` if the first branch was taken, `false` if it wasn't)

**Comment by maboesanman** [comment]
After looking into this more, I have realized that lcov supports the partial line information, so rather than explicitly supporting codecov's format, I think the documentation should just be adjusted to reflect that lcov is the recommended format for codecov rather than coveralls.

**Comment by marco-c** [comment]
@maboesanman that works for me, could you submit a PR to update the docs?
