### ISSUE TITLE
travis-ci.org shutting down tomorrow on June 15th

### ISSUE THREAD

**Issue by dnaka91** [mozilla/grcov#637]
When checking the builds of my PR I noticed that travis-ci.ORG is shutting down tomorrow as they migrate everything to a single travis-ci.COM instead of having to separate domains (probably because it caused confusion in the past).

> Hi! It seems there are still plenty of builds running. We're pushing back the shutdown date to June 15th. Please consider migrating to travis-ci.com. 

Migration should be easy, just someone with contributor rights needs to link travis-ci.com as CI to this repo.

Besides that, would there be interest in migrating to GitHub Actions?
I'm quite familiar with it and could prepare the changes to have everything run there instead.

**Comment by marco-c** [comment]
Our plan would actually be to switch to Taskcluster (#135), as we are using it for many other projects and it is super configurable.

**Comment by marco-c** [comment]
I've moved the CI to travis-ci.com, so I'm going to close this.

If you want to contribute switching to Taskcluster, it'd be great.
Otherwise, I'd also be OK with switching to GitHub Actions for the time being and switch to Taskcluster in the future.

**Comment by dnaka91** [comment]
Hm, I just updated my PRs and it seems that GitHub is not receiving any status from travis-ci.com 🤔.

Regarding Taskcluster, I never worked with it so probably a bit difficult for me to prepare the initial move over. If there is already a WIP branch or similar I'd be glad to help though.

**Comment by marco-c** [comment]
For taskcluster, you could take inspiration from https://github.com/mozilla/rust-code-analysis/blob/master/.taskcluster.yml.
Otherwise, we can try with GitHub Actions.

**Comment by marco-c** [comment]
@dnaka91 still interested in this? If you know how to use GitHub Actions well, we can move to that instead of Taskcluster for the time being (still better than no CI on Linux and Mac!)

**Comment by dnaka91** [comment]
I was looking at Taskcluster a bit but as I haven't used it myself yet, it would probably take me many iterations before we get anything useful out of that migration.

I'll start on setting up everything as GitHub Actions for now then. Shouldn't be too complicated except the compiler setups eventually.

Have to figure out how to test the GitHub Actions before merging as I'm not a collaborator of the repo. Maybe I can get it running on my fork at first and then you'd have to enable Actions on this main repo once I open the PR.

**Comment by marco-c** [comment]
@dnaka91 I've created an empty workflow you can work with, https://github.com/mozilla/grcov/commit/0164e3e4eeac5975a7f5c30daf0f2fb570575cb5.

**Comment by dnaka91** [comment]
Thanks. I think I'll be able to get started on this in the next few days 🚀
