### ISSUE TITLE
Consider disabling Windows nightly and MacOS CI tasks

### ISSUE THREAD

**Issue by dnaka91** [mozilla/grcov#641]
At the moment it seems that every time the Windows build for nightly fails with some error regarding the `regex_syntax` dependency and the MacOS build simply hangs while installing some dependency and is cancelled after 10min.

In my previous PRs it was mentioned that it's expected behavior but it makes it difficult to understand whether a PR actually broke something or not.

Therefore, could this two tasks be temporarily disabled?

### Windows

The error comes from the `regex_syntax` crate on nightly, so it might be worth trying to update dependencies and see whether it fixes things before completely disabling the task.

### MacOS

The code is being build for 10.13 and the build logs already warn that it's neither supported by Apple nor Homebrew anymore. Eventually this hanging build could be fixed by upgrading to a more recent OS version if there's nothing that's specific to 10.13 that needs to be checked?

I'm not sure why `gperftools` is built from source every time. Maybe this could be avoided with an OS upgrade as well? That specific part is what makes the run hang and it seems that's due to some java updates that are triggered in the process.

As I mentioned in #637 it may be feasible to move to GitHub Actions altogether. From personal experience with GitHub Actions, I can tell that it's MacOS support is really good and that may help in fixing the current issues as well.

**Comment by marco-c** [comment]
I'm OK with disabling these tasks until we fix them. Keeping them in failure state doesn't help.
