### ISSUE TITLE
Cobertura (xml) output coverage stats different from HTML stats

### ISSUE THREAD

**Issue by johnoneil** [mozilla/grcov#663]
This is a bit difficult to summarize except at a high level.

Running coverage stats with `html` output I get:

![Screenshot from 2021-07-21 12-50-18](https://user-images.githubusercontent.com/2950232/126551369-7ae2f08f-c0e3-4d70-a6c8-08c3660687de.png)

However, for the same input and settings, except I now specify Cobertura (xml) output, I get (summary at the top of the xml):

```
<coverage lines-covered="83498" lines-valid="398400" line-rate="0.20958333333333334" branches-covered="97972" branches-valid="1006558" branch-rate="0.0973336856892499" complexity="0" version="1.9" timestamp="1626893076">
```
Or a coverage of about 20%?

Is there some rationale for this? I might try to debug the XML/HTML output code to try and explain the difference but is there some offhand reason why this would be the case?

**Comment by marco-c** [comment]
I can't think of anything except a bug in either the HTML or the Cobertura output.

**Comment by johnoneil** [comment]
Thanks for you feedback @marco-c .

I'm still wrangling with coworkers to get set up in CI, but I might try to debug this. Traditionally i'd say backlog this but I don't think that's an option in github. So I'll just leave it open.

I can easily see the different code paths for HTML vs Cobertura generation. HTML looks multi-threaded so I did a quick pass forcing 1 thread but with no difference.

I'l bump this issue if/when I can take a look.

**Comment by svenfoo** [comment]
Might be a duplicate of #636. Are you using a released version of grcov? The latest release still has this issue.

**Comment by marco-c** [comment]
@svenfoo 0.8.1 should contain your fix.

**Comment by svenfoo** [comment]
> @svenfoo 0.8.1 should contain your fix.

Ah, I didn't realize that 0.8.1 is out, it's not listed as "Latest Release" on the GitHub project page.

**Comment by marco-c** [comment]
It wasn't published on GitHub as a release because the CI is currently partially broken, it's only on crates.io.

**Comment by johnoneil** [comment]
So a coworker and I got `grcov` up and running in CI and interesting this issue disappeared.

The original issue was encountered when running off a script so it's unlikely it's human error, but it does look like a strange side effect of access to some of the dependency source file folders, maybe due to our project structure. In CI those were present in a `cargo` folder at project root, but not during development (where they're at `~/.cargo/cache` or similar. Tough to pin down but I'm not going to worry about it.

This is all on current `grcov` release.
