### ISSUE TITLE
Binary assets missing for 0.8.1 release

### ISSUE THREAD

**Issue by mbrobbel** [mozilla/grcov#664]
The [v0.8.1 release](https://github.com/mozilla/grcov/releases/tag/v0.8.1) is missing binary assets. I had a CI job fail when trying to download the latest release using: `https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2` (as recommended in the README).

Looks like this is caused by https://github.com/mozilla/grcov/issues/637.

**Comment by marco-c** [comment]
I'll upload it manually.

**Comment by marco-c** [comment]
Done.
