### ISSUE TITLE
attempt to divide by zero

### ISSUE THREAD

**Issue by skoky** [mozilla/grcov#675]
I am getting this issue

`08:10:42 [ERROR] A panic occurred at /Users/skokan/.cargo/registry/src/github.com-1ecc6299db9ec823/grcov-0.8.2/src/html.rs:458: attempt to divide by zero`

while runining

`grcov . --binary-path ./target/debug/ -s . -t html --branch --ignore-not-existing -o ./coverage/`

on my project with grcov 0.82.0
I follow steps described here https://github.com/marco-c/rust-code-coverage-sample

**Comment by youduda** [comment]
After switching to rust-nighly as the default toolchain, did you run `rustup component add llvm-tools-preview`?

**Comment by skoky** [comment]
Yes I did

**Comment by ralpha** [comment]
For me the problem was solved after making sure the `llvm-tools-preview` was added in the nightly toolchain, not just stable.
`rustup toolchain install nightly --allow-downgrade --component llvm-tools-preview`

**Comment by bausano** [comment]
I have the same issue with following setup:

```
active toolchain
----------------

nightly-x86_64-unknown-linux-gnu
rustc 1.58.0-nightly (dd549dcab 2021-11-25)
```

Then I add `llvm-tools-preview` making sure I am on nightly. Then I run

```
cargo test --lib

grcov . -s . --binary-path ./target/debug/ -t html --branch --ignore-not-existing -o ./target/debug/coverage/
```

And I get the error:

```
... many similar errors as these:
profiling: xxx-f9cc652c76a93eba.gcda: cannot merge previous GCDA file: corrupt arc tag (0x00000000)
profiling: xxx-f9cc652c76a93eba.gcda: cannot merge previous GCDA file: mismatched number of counters (6)
profiling: xxx-f9cc652c76a93eba.gcda: cannot merge previous GCDA file: corrupt arc tag (0x00000000)
profiling: xxx-f9cc652c76a93eba.gcda: cannot merge previous GCDA file: mismatched number of counters (6)
profiling: xxx-f9cc652c76a93eba.gcda: cannot merge previous run count: corrupt object tag (0x00000000
14:38:58 [ERROR] Error in computing counters: Unexpected number of edges (in _ZN4core3ptr142drop_in_place$LT$alloc..collections..btree..map..IntoIter$LT$xxx..pubkey..Pubkey$C$xxx..models..reserve..Reserve$GT$$GT$17hd8c503abc4c80ec1E) in target/debug/deps/xxx-f9cc652c76a93eba
14:38:59 [ERROR] A panic occurred at xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/grcov-0.8.4/src/html.rs:458: attempt to divide by zero
```

This only happens the second time I run the code coverage. After `cargo clean`, everything works fine again for the first run.

**Comment by mati865** [comment]
It happens with old BFD versions, you can use LLD instead by adding `-Zgcc-ld=lld` to your RUSTFLAGS.

**Comment by sudhirdhumal289** [comment]
For me `grcov` command started working after removing `default.profraw` after `cargo build`

**Comment by jonhoo** [comment]
For reference, this is fixed in https://github.com/mozilla/grcov/pull/721, though that commit is not yet in any public release.
