### ISSUE TITLE
grcov missing a lot of lines in file

### ISSUE THREAD

**Issue by romdotdog** [mozilla/grcov#714]
I had almost no issues using grcov after almost 6 months of usage, so thanks for that :)

I'm using grcov with GitHub Actions (specifically [actions-rs/grcov](https://github.com/actions-rs/grcov)) here: 
https://github.com/romdotdog/w/blob/8eb45769c791931c51f0ecb76b318ba14733a480/.github/workflows/coverage.yml#L24

When I split my project into multiple crates though, this file went from [302 lines](https://app.codecov.io/gh/romdotdog/w/blob/f3a6465066eb68b29c4fba57ff3a75331004eb83/src/parser/mod.rs) to [1 line](https://app.codecov.io/gh/romdotdog/w/blob/8eb45769c791931c51f0ecb76b318ba14733a480/compiler/w_parser/src/lib.rs)

Thanks in advance if you find a solution

**Comment by marco-c** [comment]
@romdotdog could you try source-based coverage and see if the result is different?
https://github.com/mozilla/grcov#example-how-to-generate-source-based-coverage-for-a-rust-project

**Comment by romdotdog** [comment]
@marco-c that worked! thanks a lot, I'm happy there is an existing solution. I'd hope for there to be some sort of notice for this kind of behaviour in .gcda file coverage
