### ISSUE TITLE
Test coverage results don't seem to be right

### ISSUE THREAD

**Issue by QiangHeisenberg** [mozilla/grcov#715]
I tested the ```rand```project and found that it had zero branch coverage.

Is this normal?
![image](https://user-images.githubusercontent.com/46313511/142557754-c8bb786a-804c-4a7f-abbd-5ba14b76e26a.png)

**Comment by marco-c** [comment]
Are you using source-based coverage or gcov-based coverage?

**Comment by QiangHeisenberg** [comment]
This is based on the coverage of the source.Will the results of the two be different?

**Comment by QiangHeisenberg** [comment]
Thanks, I tested it. The results of the two are still quite different.

![image](https://user-images.githubusercontent.com/46313511/143406572-5ef29326-b081-42a0-b32c-fdeccbe38c83.png)

**Comment by QiangHeisenberg** [comment]
The reason I reopened is that I want to know what is the difference between these two test methods, and why is there such a big gap in the results of branch coverage?

**Comment by victor-aembit** [comment]
+1. 

I tried to run it against my small project (with code based coverage) and I can see quite a lot of unexpected things:

- Zero branch coverage info (even though I used "--branch" flag) (This is my biggest concern)
- Some of macros for tests marked as hit. Some tests function are included (green) and some excluded (white)
- Function coverage percentage is strangely off.  As an example, there are two functions (marked as green). However, it shows 66.67% (which implies that there is a third function, but nothing is marked as red)

**Comment by QiangHeisenberg** [comment]
> * Zero branch coverage info (even though I used "--branch" flag) (This is my biggest concern)

This is because the source-based approach does not currently support branch coverage.
refer to:https://github.com/rust-lang/rust/issues/79649

I agree to other situations. In addition, you can continue the discussion here.https://github.com/rust-lang/rust/issues/91661

**Comment by marco-c** [comment]
>The reason I reopened is that I want to know what is the difference between these two test methods, and why is there such a big gap in the results of branch coverage?

gcov-based coverage is using DebugInfo.
Source-based coverage instead is using the AST directly.

There is some information on https://clang.llvm.org/docs/SourceBasedCodeCoverage.html. It's about Clang, but should apply similarly to Rust.
