### ISSUE TITLE
After nightly update `.gcda` and `.gcno` files no longer generated

### ISSUE THREAD

**Issue by johnoneil** [mozilla/grcov#744]
We've been using `.grcov` in CI for some months now with good results.

But after a recent update of our version of rust nightly we can no longer generate either `.gcda` or `.gcno` files for coverage. Rest of our process hasn't changed, that is we still export the env variables suggested in the README, e.g. `CARGO_INCREMENTAL=0` etc.

versions:
```
cargo 1.58.0-nightly (294967c53 2021-11-29)
grcov 0.8.4
```
Specifically, `.gcda` and `.gcno` files are no longer located in any subdirectory of the Rust `target` directory, but it is possible they're being generated somewhere else on the system?

Or perhaps a mismatch of tooling?

**Comment by marco-c** [comment]
This is pretty strange, are you still able to reproduce? Maybe it was a temporary regression in Rust nightly?
What is the first Nightly with which you can reproduce the problem?

**Comment by johnoneil** [comment]
Thanks for your help @marco-c . I was hoping maybe this might ring a bell.
By running in a local docker container I was able to determine the issue doesn't seem to be coming from the nightly version we're using. Issue is currently only reproducible in a gitlab runner.
I'm going to close this but our future debug efforts will try to hunt down why we're failing in gitlab specifically.
