### ISSUE TITLE
Clean up path rewriting code

### ISSUE THREAD

**Issue by marco-c** [mozilla/grcov#76]
It was rewritten several times to cope with new corner cases. Now that everything works, I think the code should be rewritten from scratch to make it cleaner and to make it clearer what the path-mapping, prefix and source-dir options do by untangling them.

**Comment by marco-c** [comment]
- path mapping; if a mapping file is specified, rewrite paths in the coverage data using this mapping;
- source directory; if a source directory is specified, try to resolve symlinks;
- strip prefix; strip the prefix from the paths before attempting the symlink resolution and after applying the mapping and symlink resolution.

**Comment by Juniar-II** [comment]
Which files or directory should be rewritten, there are many files from the source code? Which mapping techniques or prefix should be used, can you give an example?

**Comment by marco-c** [comment]
We don't have to rewrite the files and directories of this repo :smile: 
We have to modify the path rewriting code in src/path_rewriting.rs to simplify it as I suggested in the first two comments.

**Comment by marco-c** [comment]
#192 removed some now unused options, #194 is doing the additional cleanup.
