### ISSUE TITLE
 0.8.5 always reports 0% in coverage.json 

### ISSUE THREAD

**Issue by dawn-minion** [mozilla/grcov#763]
It seems the coverage.json file generated for shields.io is broken in 0.8.5, as it now always reports 0% coverage. The HTML file created is still correct and shows the right coverage stats. Reverting to 0.8.4 fixes it, and the project then shows the correct percentage again.

With 0.8.5:
```json
{"schemaVersion":1,"label":"coverage","message":"0%","color":"red"}
```

And 0.8.4:
```json
{"schemaVersion":1,"label":"coverage","message":"24%","color":"red"}
```

Args:
```
grcov . --binary-path ./target/debug/ -s . -t html --branch --ignore "*cargo*" -o ./coverage.xml --excl-br-start "mod tests \{" --excl-start "mod test \{"  --prefix-dir /src/ .
```

Project is in Rust, with version `rustc 1.60.0-nightly (84322efad 2022-01-23)`, with latest llvm-tools-preview. It happens with both profraw files and gcda/gcno files.

**Comment by marco-c** [comment]
Could you try running a bisection to figure out what caused this?
If not, could you provide the source code of the project so we can try running the bisection ourselves?

**Comment by JohnnyMorganz** [comment]
I'm also getting this problem when using 0.8.7 on https://github.com/JohnnyMorganz/StyLua with the default command in the README (`grcov . -s . --binary-path ./target/debug/ -t html --branch --ignore-not-existing -o ./target/debug/coverage/`).
I can look into a bisection, but it currently takes me ~8 minutes to output a report each time, so I'll have to set aside some time later
