### ISSUE TITLE
Publish release job is failing

### ISSUE THREAD

**Issue by marco-c** [mozilla/grcov#766]
Example failure for v0.8.6: https://github.com/mozilla/grcov/runs/4981796409?check_suite_focus=true

CC @dnaka91

**Comment by dnaka91** [comment]
Could it be that repository permissions changed? The request returns a 403 error so the token might not have enough rights.

For example, there is a setting to switch the token to read-only rights and that would make this job fail.

**Comment by marco-c** [comment]
All right, it's working now. The releases are created as draft, which is good. They don't completely match the format we were using for the previous releases (title and description were empty), but I can for now simply manually edit them before publishing.

**Comment by dnaka91** [comment]
There are several community actions that can create nice release notes automatically. They extract the right section from the CHANGELOG.md and add them as body.

One of those is https://github.com/taiki-e/create-gh-release-action, and there are many more with more stars as well. It would make things a lot easier, but I guess that needs some work from your side to get approval for using the action.

Maybe it's worth a thought to fork some actions, give them a short review and use the fork instead? That would give Mozilla full control over the action 🤔
