### ISSUE TITLE
Cannot link to "latest" release artifacts due to explicit version

### ISSUE THREAD

**Issue by snue** [mozilla/grcov#774]
Since the switch to Github Actions the artifacts in the releases contain the version in their name. This breaks the [automatic github link forwarding](https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases) from `https://github.com/mozilla/grcov/releases/latest/download/artifact_name`.

The version should either be removed from the artifact name, or an additional symlink without version should be provided at least for the linux build used in typical CI setups (as documented in the README).

See also #769 and #770

**Comment by alexschrod** [comment]
+1, one of my builds have started failing not due to any changes I made, but because the url <https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2> went from existing to returning a 404.

**Comment by marco-c** [comment]
I won't have time to fix this any time soon, but I'd be happy to review patches.

**Comment by snue** [comment]
Thanks for the quick review/merge. Now we just have to wait for the next release so the examples in the README start working aagin. :wink:
