### ISSUE TITLE
Coverage statistics

### ISSUE THREAD

**Issue by silence-coding** [mozilla/grcov#788]
Why are these also considered uncovered, and how can we solve this problem?

CMD:
`grcov . -s . --binary-path ./target/debug/ -t html --branch --ignore-not-existing -o ./target/debug/coverage/ `

![image](https://user-images.githubusercontent.com/32766901/156179387-991d9d86-d5aa-4a74-a5ae-22ed4a99c648.png)
![image](https://user-images.githubusercontent.com/32766901/156179423-5535391d-afc5-41aa-84a0-3a15ec417827.png)

**Comment by calixteman** [comment]
The code is instrumented by some llvm stuff which relies on the debug info.
Here `derive(Clone)` adds some hidden code and the debug info for it are on the struct definition.

**Comment by silence-coding** [comment]
![image](https://user-images.githubusercontent.com/32766901/156352232-1537bad1-1184-49e1-ab95-3b77a246f041.png)

**Comment by silence-coding** [comment]
Thanks, the problem of strucrt not being overwritten is solved, but I have a question as to why this encode_cert does not have any flags, and I can confirm that it was called.

**Comment by silence-coding** [comment]
The source-based coverage for a Rust project does not have this problem.
