### ISSUE TITLE
cannot merge previous GCDA file

### ISSUE THREAD

**Issue by Ilqjx** [mozilla/grcov#812]
Hi, I am using grcov for the first time, and then I found this problem, `cannot merge previous GCDA file`, I need to delete this GCDA file every time to solve it.

**Comment by marco-c** [comment]
This is expected: when you recompile your program, you have effectively built a different program than before. Using coverage information from a previous run of a different build is not feasible.

**Comment by Ilqjx** [comment]
Ok, thanks a lot.
