### ISSUE TITLE
Any way to ignore/exclude a file or folder?

### ISSUE THREAD

**Issue by Ilqjx** [mozilla/grcov#816]

**Comment by Ilqjx** [comment]
The generated report includes the files in target/debug, is there any way to skip it?

**Comment by marco-c** [comment]
There is an `--ignore` option.

**Comment by Ilqjx** [comment]
I tried, but `--ignore target/debug` didn't work.

**Comment by wilwade** [comment]
@Ilqjx `--ignore "target/**/*"` will work
