### ISSUE TITLE
  Please publish a release for 0.8.9

### ISSUE THREAD

**Issue by federicomenaquintero** [mozilla/grcov#837]
It seems that the latest tag is 0.8.9, but the latest release in github is 0.8.7.  Could you please make a new one? :)

**Comment by thomcc** [comment]
Given that the CI for these releases succeeded (https://github.com/mozilla/grcov/actions/workflows/release.yml), and that it contains https://github.com/mozilla/grcov/blob/cbc92160d01496bfcbd0a1e7295452353f7da3e5/.github/workflows/release.yml#L141 it seems likely that someone (CC @marco-c) needs to go into the releases list and just mark the draft release as not a draft.

**Comment by marco-c** [comment]
0.8.8 and 0.8.9 released!
