### ISSUE TITLE
Windows "The filename or extension is too long"

### ISSUE THREAD

**Issue by milesj** [mozilla/grcov#838]
Seeing this weird issue where grcov (I think) fails with "The filename or extension is too long. (os error 206)" when trying to run on Windows with a bunch of sources. You can see the output here: https://github.com/moonrepo/moon/runs/6747703502?check_suite_focus=true

When looking at the list of file paths, _none_ of these are long, nor do they have incorrect file names/extensions. I'm confused on how to fix this. Maybe it's `/` instead of `\`?

Another related issue is that grcov fails, but the build is still green. Can this error be bubbled up to not be a 0 exit code?

**Comment by marco-c** [comment]
Maybe same issue as #695?

I'll submit a PR to return a !0 exit code in this case.

**Comment by obsgolem** [comment]
I have a fix for this; `llvm-profdata merge` can actually take a `-f -` parameter which lets you pass an arbitrary number of filenames. PR incoming.
