### ISSUE TITLE
Top level page is broken when there is source file in top level

### ISSUE THREAD

**Issue by funbiscuit** [mozilla/grcov#845]
In my rust project I use sqlx. So there is a `build.rs` file alongside Cargo.toml to recompile source when migrations change. If I generate html coverage, top level directory is broken. It contains this build.rs file and not links to all subdirectories. It also has `top_level` link which points outside of output directory which doesn't contain anything.
This is an example:
![image](https://user-images.githubusercontent.com/9351181/173277724-ed78785b-fa05-44da-9836-3480205bf461.png)

The way I fix this currently is by adding `--ignore build.rs`. This way root page is generated correctly:
![image](https://user-images.githubusercontent.com/9351181/173277827-faa97640-a9d7-45a1-8b6f-73f4af309004.png)

In this case `top_level` is not a link and all subdirectories are listed.

I think the best solution to this problem would be to change how output looks like. And on each page include both files in this directories and all child directories. So in my case root page and src directory should look like this (I created it manually to show the concept):

![image](https://user-images.githubusercontent.com/9351181/173278276-7a44b4cd-25da-4c68-85eb-ec53725c4ea7.png)

![image](https://user-images.githubusercontent.com/9351181/173278238-7da33ebe-eba5-42bf-aff0-96d61a9b4dc7.png)

**Comment by marco-c** [comment]
> I think the best solution to this problem would be to change how output looks like. And on each page include both files in this directories and all child directories. So in my case root page and src directory should look like this (I created it manually to show the concept):

Yeah, we should definitely do this!

**Comment by zedseven** [comment]
Just thought I'd mention I'm having the same issue, version 0.8.11.

I only stumbled on the fix accidentally, by adding `--ignore build.rs` since I didn't want that included anyway.
