### ISSUE TITLE
It says that llvm-profdata is missing but its on PATH

### ISSUE THREAD

**Issue by refaelsh** [mozilla/grcov#848]
I am rediscovering NixOS and trying to setup a development environment for Rust.
So far, I have the following default.nix file in my repo:

```
# default.nix
with import <nixpkgs> { };
stdenv.mkDerivation {
  name = "dev-environment";
  buildInputs = [
    pkg-config
    openssl
    libgit2
    zlib
    rustc
    cargo
    llvm
    rustc.llvmPackages.llvm
    grcov
    wxGTK30-gtk3
  ];
}
```

Everything works except code coverage. Here is what happens when I run grcov:

```
❯ grcov . -s . --binary-path target/debug/
17:47:35 [ERROR] Error while executing llvm tools: We couldn't find llvm-profdata. Try installing the llvm-tools component with `rustup component add llvm-tools-preview`.
```

But llvm-profdata does exists on PATH:

```
❯ llvm-profdata
llvm-profdata: No command specified!
USAGE: llvm-profdata <merge|show|overlap> [args...]
```

I dont know how to solve it. Please help :-)

**Comment by marco-c** [comment]
Did you install the `llvm-tools-preview` component?

**Comment by refaelsh** [comment]
> Did you install the `llvm-tools-preview` component?

Yes, I did. But not via `rustup`. I prefer to use my distro's (NixOS) package manager to install Rust (rustc, cargo, rustfmt and etc).
The package for `llvm-tools-preview` is called `rustc.llvmPackages.llvm` and I have it installed.

**Comment by obsgolem** [comment]
The `llvm-profdata` to use is hardcoded to the one shipped by rustup. Ideally this could take that value either as a command line parameter or find it on the PATH.

**Comment by obsgolem** [comment]
I have a fix for this on the way.

**Comment by axelkar** [comment]
Hi, just got the same issue. Why doesn't grcov just read it from PATH?

**Comment by marco-c** [comment]
@axelkar you can use the --llvm-path option.
