### ISSUE TITLE
Support parsing Jacoco artifacts

### ISSUE THREAD

**Issue by marco-c** [mozilla/grcov#92]
An example artifact is at https://github.com/marco-c/grcov/blob/master/test/basic-jacoco.xml.

**Comment by gabriel-v** [comment]
Is [xml-rs](https://github.com/netvl/xml-rs) okay to use? It's the most popular one.

Your hints were:
- make [dir_producer](https://github.com/marco-c/grcov/blob/1311c289426a547c4c529809341ab5d7af2cfd7e/src/producer.rs#L12) find .xml files
- implement parsing those jacoco xml files, start from [parse_gcov](https://github.com/marco-c/grcov/blob/a06e7294b9e1e1cbb1c70f0a58bfb3012f2c6e2d/src/parser.rs#L320)
- wait for https://github.com/marco-c/grcov/pull/129 as it changes relevant portions

**Comment by marco-c** [comment]
`xml-rs` sounds good!

> make dir_producer find .xml files

Both dir_producer and zip_producer (after #129 there should be a single one). Look at the `info` case, as that's the most similar one (for gcno/gcda we have couples of files, for info we have all the data in single files).

> implement parsing those jacoco xml files, start from parse_gcov

Yep, you can either look at parse_lcov or parse_gcov, they are the most simple formats.

> wait for #129 as it changes relevant logic

You can actually already start, the changes to `producer` will require some rebasing, but it should be very simple.
